# Generated by GitHub Copilot
"""GitHub integration routes."""

from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session

from database import get_db
from models import Release
from schemas import GitHubPullRequestResponse
from services.github_service import (
    get_pull_request,
    get_pull_requests,
    get_release_pull_requests,
    remap_all_pull_requests_to_release,
    sync_all_mapped_pull_requests,
    sync_project_pull_requests,
    sync_pull_requests,
)
from github_client import get_milestones
from services.github_service import GITHUB_TOKEN, GITHUB_OWNER, GITHUB_REPO

router = APIRouter(prefix="/api/github", tags=["GitHub"])


# Generated by GitHub Copilot
def _to_pr_response(prs: list[dict]) -> list[GitHubPullRequestResponse]:
    """Map GitHub payloads to response schema."""
    response: list[GitHubPullRequestResponse] = []
    for pr in prs:
        user = pr.get("user") or {}
        response.append(
            GitHubPullRequestResponse(
                number=pr.get("number") or 0,
                title=pr.get("title") or "",
                state=pr.get("state") or "open",
                author=user.get("login") or "unknown",
            )
        )
    return response


@router.get("/prs", response_model=list[GitHubPullRequestResponse], summary="Fetch live GitHub PRs")
def fetch_github_prs(repository: str | None = Query(default=None, description="owner/repo"), state: str = Query(default="open", description="open|closed|all")) -> list[GitHubPullRequestResponse]:
    """Fetch pull requests from GitHub API."""
    return _to_pr_response(get_pull_requests(repository=repository, state=state))


@router.get("/prs/{pr_number}", summary="Fetch one GitHub PR")
def fetch_github_pr(pr_number: int, repository: str | None = Query(default=None, description="owner/repo")) -> dict:
    """Fetch one pull request from GitHub API."""
    return get_pull_request(pr_number, repository=repository)


@router.post("/releases/{release_id}/prs/sync", summary="Sync GitHub PRs to a release")
def sync_release_prs(release_id: int, state: str = Query(default="all", description="open|closed|all"), db: Session = Depends(get_db)) -> dict:
    """Sync GitHub pull requests into local DB for a release."""
    return sync_pull_requests(db, release_id, state=state)


@router.post("/projects/{project_id}/prs/sync", summary="Sync GitHub PRs for one project")
def sync_project_prs(
    project_id: int,
    state: str = Query(default="all", description="open|closed|all"),
    release_id: int | None = Query(default=None, description="optional target release_id for all synced PRs"),
    db: Session = Depends(get_db),
) -> dict:
    """Sync GitHub pull requests using project repository mapping."""
    return sync_project_pull_requests(db, project_id, state=state, release_id=release_id)


@router.post("/prs/sync-all", summary="Sync GitHub PRs for all mapped repositories")
def sync_all_prs(
    state: str = Query(default="all", description="open|closed|all"),
    release_id: int | None = Query(default=None, description="optional target release_id for all synced PRs"),
    db: Session = Depends(get_db),
) -> dict:
    """Sync GitHub pull requests for all configured project repositories."""
    return sync_all_mapped_pull_requests(db, state=state, release_id=release_id)


# Generated by GitHub Copilot
@router.delete(
    "/releases/{release_id}/prs/cleanup-nullrepo",
    summary="Remove duplicate PR rows that have no repository set",
)
def cleanup_null_repo_prs(release_id: int, db: Session = Depends(get_db)) -> dict:
    """Delete pull_request rows for a release where ``repository IS NULL``.

    These are orphaned duplicates created when PRs were first synced before
    the repository field was resolved, and later re-synced with the correct
    repository name, leaving two rows per PR number.
    """
    from models import PullRequest
    rows = (
        db.query(PullRequest)
        .filter(
            PullRequest.release_id == release_id,
            PullRequest.repository.is_(None),
        )
        .all()
    )
    count = len(rows)
    for row in rows:
        db.delete(row)
    db.commit()
    return {"release_id": release_id, "deleted": count}


@router.post("/prs/remap-release/{release_id}", summary="Remap all stored PRs to one release")
def remap_prs_to_release(release_id: int, db: Session = Depends(get_db)) -> dict:
    """Force-map all pull_requests rows to the specified release id."""
    return remap_all_pull_requests_to_release(db, release_id=release_id)


# Generated by GitHub Copilot
@router.post(
    "/prs/remap-by-milestone-version",
    summary="Remap each PR to the release whose version matches its milestone_version",
)
def remap_prs_by_milestone_version(db: Session = Depends(get_db)) -> dict:
    """For every pull_request row that has a ``milestone_version`` set, look up
    the release whose ``version`` column matches (case-insensitive, optional
    leading 'v' stripped) and update ``release_id`` accordingly.

    PRs whose ``milestone_version`` does not match any release are left
    unchanged so no data is lost.

    Returns a per-version breakdown of how many rows were reassigned.
    """
    from models import PullRequest

    releases = db.query(Release).all()

    # Build normalised version → release mapping
    version_to_release: dict[str, Release] = {}
    for rel in releases:
        if rel.version and rel.version.upper() != "UNVERSIONED":
            key = rel.version.lstrip("vV").lower()
            version_to_release[key] = rel

    prs = db.query(PullRequest).filter(PullRequest.milestone_version.isnot(None)).all()

    summary: dict[str, dict] = {}

    for pr in prs:
        ms_ver = (pr.milestone_version or "").lstrip("vV").lower()
        target_release = version_to_release.get(ms_ver)
        if not target_release:
            continue

        ver_label = pr.milestone_version
        if ver_label not in summary:
            summary[ver_label] = {
                "version": ver_label,
                "release_id": target_release.release_id,
                "release_name": target_release.release_name,
                "prs_remapped": 0,
            }

        if pr.release_id != target_release.release_id:
            pr.release_id = target_release.release_id
            summary[ver_label]["prs_remapped"] += 1

    db.commit()

    return {
        "total_remapped": sum(v["prs_remapped"] for v in summary.values()),
        "breakdown": list(summary.values()),
    }


# Generated by GitHub Copilot
@router.post(
    "/releases/{release_id}/prs/backfill-version",
    summary="Backfill milestone_version for existing PRs from release version",
)
def backfill_pr_versions(release_id: int, db: Session = Depends(get_db)) -> dict:
    """Populate ``milestone_version`` on every pull request row that belongs to
    this release but currently has a NULL value.

    Root cause this solves:
    - PRs synced before the milestone_version column existed have NULL values.
    - GitHub PRs without an assigned milestone return ``milestone: null``,
      so the sync never fills the column automatically.

    This endpoint fills the gap by stamping the release's own ``version`` string
    onto every NULL row, making version-based filtering work immediately.
    """
    release = db.query(Release).filter(Release.release_id == release_id).first()
    if not release:
        from fastapi import HTTPException
        raise HTTPException(status_code=404, detail=f"Release {release_id} not found")

    if not release.version or release.version.upper() == "UNVERSIONED":
        return {
            "release_id": release_id,
            "release_name": release.release_name,
            "skipped": True,
            "reason": "Release has no version set (UNVERSIONED). Set a version first.",
            "updated": 0,
        }

    from models import PullRequest
    rows = (
        db.query(PullRequest)
        .filter(
            PullRequest.release_id == release_id,
            PullRequest.milestone_version.is_(None),
        )
        .all()
    )

    for pr in rows:
        pr.milestone_version = release.version

    db.commit()

    return {
        "release_id": release_id,
        "release_name": release.release_name,
        "version_applied": release.version,
        "updated": len(rows),
    }


@router.get("/releases/{release_id}/prs", summary="Fetch locally stored PRs for a release")
def release_prs(release_id: int, db: Session = Depends(get_db)) -> list[dict]:
    """Return local pull requests for release."""
    rows = get_release_pull_requests(db, release_id)
    return [
        {
            "pr_id": r.pr_id,
            "release_id": r.release_id,
            "pr_number": r.pr_number,
            "title": r.title,
            "author": r.author,
            "repository": r.repository,
            "status": r.status,
            "lines_added": r.lines_added,
            "lines_deleted": r.lines_deleted,
            "merged_date": r.merged_date,
            "jira_ref": r.jira_ref,
            "github_url": r.github_url,
            "created_at": r.created_at,
            "milestone_version": r.milestone_version,
        }
        for r in rows
    ]


# Generated by GitHub Copilot
@router.get("/milestones/mapped", summary="Fetch GitHub milestones and map to release versions")
def fetch_milestones_mapped(
    repository: str | None = Query(default=None, description="owner/repo – defaults to OWNER/REPO env vars"),
    state: str = Query(default="all", description="open | closed | all"),
    db: Session = Depends(get_db),
) -> list[dict]:
    """Fetch milestones from GitHub and map each one to a release row by version.

    Matching is done by comparing the milestone title (case-insensitive, with
    optional leading 'v' stripped) against the ``version`` column of the
    releases table.

    Returns a list of milestone objects, each augmented with a
    ``matched_release`` key (release_id, release_name, status) when a
    matching release is found, or ``null`` when no match exists.
    """
    if repository:
        parts = repository.split("/", 1)
        owner, repo = (parts[0], parts[1]) if len(parts) == 2 else (GITHUB_OWNER or "", parts[0])
    else:
        owner, repo = GITHUB_OWNER or "", GITHUB_REPO or ""

    if not owner or not repo:
        return []

    milestones = get_milestones(owner=owner, repo=repo, token=GITHUB_TOKEN, state=state)

    releases = db.query(Release).all()

    # Build version lookup: normalised version string -> Release
    version_map: dict[str, Release] = {}
    for rel in releases:
        if rel.version and rel.version.upper() != "UNVERSIONED":
            version_map[rel.version.lstrip("vV").lower()] = rel

    result = []
    for ms in milestones:
        title: str = ms.get("title") or ""
        normalised_title = title.lstrip("vV").lower()
        matched = version_map.get(normalised_title)
        result.append({
            "milestone_number": ms.get("number"),
            "title": title,
            "state": ms.get("state"),
            "due_on": ms.get("due_on"),
            "open_issues": ms.get("open_issues", 0),
            "closed_issues": ms.get("closed_issues", 0),
            "html_url": ms.get("html_url"),
            "matched_release": {
                "release_id": matched.release_id,
                "release_name": matched.release_name,
                "version": matched.version,
                "status": matched.status,
            } if matched else None,
        })

    return result


# Generated by GitHub Copilot
@router.post(
    "/milestones/{milestone_number}/apply-to-release/{release_id}",
    summary="Link a GitHub milestone to a release and populate version",
)
def apply_milestone_to_release(
    milestone_number: int,
    release_id: int,
    repository: str | None = Query(default=None, description="owner/repo"),
    db: Session = Depends(get_db),
) -> dict:
    """Fetch one GitHub milestone and apply its title as the version on the target
    release.  Also stamps ``milestone_version`` on every pull request belonging to
    that release so the PR table stays consistent.

    This is the correct way to resolve a release_name mismatch: explicitly tell
    the system which milestone belongs to which release, and the version column
    is updated accordingly.
    """
    if repository:
        parts = repository.split("/", 1)
        owner, repo = (parts[0], parts[1]) if len(parts) == 2 else (GITHUB_OWNER or "", parts[0])
    else:
        owner, repo = GITHUB_OWNER or "", GITHUB_REPO or ""

    if not owner or not repo:
        from fastapi import HTTPException
        raise HTTPException(status_code=400, detail="Repository owner/repo is required")

    milestones = get_milestones(owner=owner, repo=repo, token=GITHUB_TOKEN, state="all")
    milestone = next((m for m in milestones if m.get("number") == milestone_number), None)
    if not milestone:
        from fastapi import HTTPException
        raise HTTPException(status_code=404, detail=f"Milestone {milestone_number} not found in {owner}/{repo}")

    release = db.query(Release).filter(Release.release_id == release_id).first()
    if not release:
        from fastapi import HTTPException
        raise HTTPException(status_code=404, detail=f"Release {release_id} not found")

    milestone_title: str = milestone.get("title") or ""

    # Update version on the release
    release.version = milestone_title

    # Stamp milestone_version on every pull request for this release
    from models import PullRequest
    updated_prs = (
        db.query(PullRequest)
        .filter(PullRequest.release_id == release_id)
        .all()
    )
    for pr in updated_prs:
        pr.milestone_version = milestone_title

    db.commit()

    return {
        "release_id": release_id,
        "release_name": release.release_name,
        "version_set_to": milestone_title,
        "pull_requests_updated": len(updated_prs),
    }
