# Generated by GitHub Copilot
"""Jira integration routes."""

from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session

from database import get_db
from schemas import JiraIssueResponse
from services.jira_service import (
    get_issue,
    get_issue_release_map,
    get_issues,
    get_live_projects,
    get_release_issues,
    get_stored_projects,
    sync_project_issues,
    sync_projects,
    sync_release_issues,
)

router = APIRouter(prefix="/api/jira", tags=["Jira"])


# Generated by GitHub Copilot
def _to_issue_response(issues: list[dict], issue_release_map: dict[str, int | None]) -> list[JiraIssueResponse]:
    """Convert Jira issue payloads to response schema."""
    response: list[JiraIssueResponse] = []
    for issue in issues:
        fields = issue.get("fields", {})
        status_obj = fields.get("status") or {}
        priority_obj = fields.get("priority") or {}
        assignee_obj = fields.get("assignee") or {}
        key = issue.get("key") or ""
        response.append(
            JiraIssueResponse(
                key=key,
                summary=fields.get("summary") or "",
                status=status_obj.get("name") or "Unknown",
                priority=priority_obj.get("name") or "Medium",
                assignee=assignee_obj.get("displayName") or "Unassigned",
                release_id=issue_release_map.get(key),
            )
        )
    return response


@router.get("/projects/live", summary="Fetch projects directly from Jira")
def live_projects() -> list[dict]:
    """Return projects from Jira Cloud."""
    return get_live_projects()


@router.get("/projects/stored", summary="Fetch Jira-synced projects from DB")
def stored_projects(db: Session = Depends(get_db)) -> list[dict]:
    """Return Jira-capable projects from local storage."""
    rows = get_stored_projects(db)
    return [
        {
            "project_id": p.project_id,
            "project_name": p.project_name,
            "jira_project": p.jira_project,
            "repository_name": p.repository_name,
        }
        for p in rows
    ]


@router.post("/projects/sync", summary="Sync Jira projects to DB")
def sync_projects_to_db(db: Session = Depends(get_db)) -> dict:
    """Trigger Jira project sync into database."""
    return sync_projects(db)


@router.get("/projects/{project_key}/issues", response_model=list[JiraIssueResponse], summary="Fetch Jira issues for a project")
def project_issues(project_key: str, db: Session = Depends(get_db)) -> list[JiraIssueResponse]:
    """Fetch project issues from Jira and include local release mappings."""
    issues = get_issues(project_key)
    issue_release_map = get_issue_release_map(db, [issue.get("key") or "" for issue in issues])
    return _to_issue_response(issues, issue_release_map)


@router.post("/projects/{project_key}/issues/sync", summary="Sync Jira project issues to DB")
def sync_project_issues_to_db(project_key: str, release_id: int | None = Query(default=None), db: Session = Depends(get_db)) -> dict:
    """Sync Jira issues for one project into local work items."""
    return sync_project_issues(db, project_key, release_id=release_id)


@router.get("/issues/detail/{issue_key}", summary="Fetch Jira issue details")
def issue_detail(issue_key: str) -> dict:
    """Return full Jira issue details."""
    return get_issue(issue_key)


@router.post("/releases/{release_id}/issues/sync", summary="Attach Jira issues to a release")
def sync_release(release_id: int, db: Session = Depends(get_db)) -> dict:
    """Sync Jira issues to a specific release."""
    return sync_release_issues(db, release_id)


@router.get("/releases/{release_id}/issues", summary="Fetch locally stored issues for a release")
def release_issues(release_id: int, db: Session = Depends(get_db)) -> list[dict]:
    """Return local work items for a release."""
    rows = get_release_issues(db, release_id)
    return [
        {
            "work_item_id": r.work_item_id,
            "release_id": r.release_id,
            "issue_key": r.issue_key,
            "title": r.title,
            "issue_type": r.issue_type,
            "priority": r.priority,
            "status": r.status,
            "assigned_to": r.assigned_to,
        }
        for r in rows
    ]
