# Generated by GitHub Copilot
"""Jira integration routes for live issue fetch and release sync."""

from typing import Optional
import logging

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from sqlalchemy import text
from sqlalchemy.orm import Session
from sqlalchemy.sql import func

from database import engine, get_db
from jira_client import fetch_project_issues, fetch_workspace_projects
from models import Project, Release, WorkItem
from project_filters import is_excluded_project_name

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/jira", tags=["Jira"])


class JiraIssue(BaseModel):
    key: str
    summary: str
    status: str
    priority: Optional[str] = None
    assignee: Optional[str] = None
    issue_type: Optional[str] = None
    release_id: Optional[int] = None
    affects_version: Optional[str] = None  # JIRA Affects Version mapped to release version


class JiraSyncRequest(BaseModel):
    project_key: str


class JiraSyncResponse(BaseModel):
    total_fetched: int
    newly_synced: int
    already_existed: int
    issues: list[JiraIssue]


class JiraWorkspaceSyncResponse(BaseModel):
    total_projects_from_jira: int
    projects_created: int
    projects_existing: int
    releases_created: int
    releases_existing: int
    work_items_inserted: int
    work_items_updated: int
    project_keys_synced: list[str]


# Generated by GitHub Copilot
def _resolve_or_create_release_for_issue(
    db: Session,
    project: Project,
    selected_version_id: str | None,
    selected_version_name: str | None,
    counts: dict[str, int],
) -> Release | None:
    """
    Resolve release by project/version or create one when needed.

    Logic:
    1. Prefer Jira version id as the lookup key into releases.version
    2. Fallback to Jira version name if id lookup does not match
    3. If still not found, create release using the best available version token
    4. If no version info at all, fall back to the latest existing release for the project
    4. After db.flush(), release_id is auto-generated and available
    """
    if not selected_version_id:
        # Fall back to the latest existing release for this project
        latest = (
            db.query(Release)
            .filter(Release.project_id == project.project_id)
            .order_by(Release.release_id.desc())
            .first()
        )
        if latest:
            counts["releases_existing"] += 1
            return latest
        return None

    version_candidates: list[str] = []
    if selected_version_id:
        version_candidates.append(str(selected_version_id))
    if selected_version_name and selected_version_name not in version_candidates:
        version_candidates.append(selected_version_name)
    if not version_candidates:
        version_candidates.append("UNVERSIONED")

    existing_release = None
    for version_value in version_candidates:
        existing_release = (
            db.query(Release)
            .filter(
                Release.project_id == project.project_id,
                Release.version == version_value,
            )
            .first()
        )
        if existing_release:
            break

    if existing_release:
        # Release already exists - reuse it as-is.
        counts["releases_existing"] += 1
        return existing_release

    version_value = version_candidates[0]

    # Create new release with auto-generated release_id
    new_release = Release(
        project_id=project.project_id,
        release_name=project.project_name,
        version=version_value,
        status="In Progress",
        created_date=func.now(),
    )
    db.add(new_release)
    db.flush()  # Ensures release_id is auto-generated and available
    
    counts["releases_created"] += 1
    return new_release


# Generated by GitHub Copilot
def _upsert_work_item(
    db: Session,
    issue: dict,
    release: Release,
    counts: dict[str, int],
) -> None:
    """
    Insert or update one work item and map it to the resolved release.
    
    Ensures:
    - issue_key is the unique identifier
    - release_id is ALWAYS populated (never null) for Jira-synced items
    - Release MUST be provided (never None)
    - Updates existing items, inserts new ones
    - NEVER skips items
    """
    if not release:
        logger.warning(f"Cannot upsert work item {issue.get('key')} - no release provided")
        return
    
    issue_key = issue["key"]
    affects_ver = issue.get("selected_version") or None

    payload = {
        "title": issue["summary"],
        "status": issue["status"],
        "priority": issue["priority"] if issue.get("priority") else "Medium",
        "assigned_to": issue.get("assignee"),
        "issue_type": issue.get("issue_type"),
        "affects_version": affects_ver,
    }

    # If the issue has an Affects Version, try to find the matching release
    # by comparing against releases.version (normalised, strip leading 'v').
    resolved_release = release
    if affects_ver:
        norm_av = affects_ver.lstrip("vV").lower()
        all_releases = db.query(Release).all()
        for rel in all_releases:
            if rel.version and rel.version.lstrip("vV").lower() == norm_av:
                resolved_release = rel
                break

    try:
        # Check if work item already exists for this specific release
        work_item = db.query(WorkItem).filter(
            WorkItem.issue_key == issue_key,
            WorkItem.release_id == resolved_release.release_id,
        ).first()
        if not work_item:
            # Also check across all releases (avoid cross-release duplicates)
            work_item = db.query(WorkItem).filter(
                WorkItem.issue_key == issue_key,
            ).first()
        if work_item:
            for field, value in payload.items():
                setattr(work_item, field, value)
            work_item.release_id = resolved_release.release_id
            counts["work_items_updated"] += 1
            logger.debug(f"Updated work item {issue_key} -> release {resolved_release.release_id} (affects_version={affects_ver})")
            return

        # Create new work item
        new_item = WorkItem(
            issue_key=issue_key,
            release_id=resolved_release.release_id,
            title=payload["title"],
            status=payload["status"],
            priority=payload["priority"],
            assigned_to=payload["assigned_to"],
            issue_type=payload["issue_type"],
            affects_version=affects_ver,
        )
        db.add(new_item)
        counts["work_items_inserted"] += 1
        logger.debug(f"Inserted work item {issue_key} -> release {resolved_release.release_id} (affects_version={affects_ver})")
    except Exception as e:
        logger.error(f"Error upserting work item {issue_key}: {e}")
        raise


# Generated by GitHub Copilot
def _sync_workspace_projects_and_issues(db: Session) -> JiraWorkspaceSyncResponse:
    """
    Sync Jira workspace projects and issues into local project/release/work_item tables.
    
    Flow:
    1. Fetch all projects from Jira workspace
    2. For each project:
       a. Create or update local Project record
       b. Fetch all issues for that project
       c. For each issue:
          - Extract affected versions (affects/fix/versions)
          - Find or create Release by (project_id, version)
          - Create or update WorkItem linked to Release
    3. Commit all changes
    
    Ensures:
    - Releases are unique per (project_id, version)
    - All WorkItems have release_id populated
    - No duplicates are created
    """
    try:
        jira_projects = fetch_workspace_projects()
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Jira API error while listing projects: {exc}") from exc

    counts = {
        "projects_created": 0,
        "projects_existing": 0,
        "releases_created": 0,
        "releases_existing": 0,
        "work_items_inserted": 0,
        "work_items_updated": 0,
    }
    synced_keys: list[str] = []

    for jira_project in jira_projects:
        project_key = jira_project.get("key")
        project_name = jira_project.get("name") or project_key
        if not project_key:
            continue
        if is_excluded_project_name(project_name):
            continue

        # Find or create Project
        project = db.query(Project).filter(Project.jira_project == project_key).first()
        if project:
            if project.project_name != project_name:
                project.project_name = project_name
            counts["projects_existing"] += 1
        else:
            project = Project(project_name=project_name, jira_project=project_key)
            db.add(project)
            db.flush()  # Ensures project_id is available
            counts["projects_created"] += 1

        # Fetch issues for this project
        try:
            issues = fetch_project_issues(project_key)
        except Exception as exc:
            raise HTTPException(status_code=502, detail=f"Jira API error while fetching issues for {project_key}: {exc}") from exc

        # Process each issue
        for issue in issues:
            # Resolve or create Release based on (project_id, version)
            release = _resolve_or_create_release_for_issue(
                db,
                project,
                issue.get("selected_version_id"),
                issue.get("selected_version"),
                counts,
            )
            
            # Upsert WorkItem mapped to Release
            _upsert_work_item(db, issue, release, counts)

        synced_keys.append(project_key)

    db.commit()

    return JiraWorkspaceSyncResponse(
        total_projects_from_jira=len(jira_projects),
        projects_created=counts["projects_created"],
        projects_existing=counts["projects_existing"],
        releases_created=counts["releases_created"],
        releases_existing=counts["releases_existing"],
        work_items_inserted=counts["work_items_inserted"],
        work_items_updated=counts["work_items_updated"],
        project_keys_synced=synced_keys,
    )


# Generated by GitHub Copilot
def _sync_project_issues_to_release(
    release_id: int,
    project_key: str,
    db: Session,
) -> JiraSyncResponse:
    """Sync Jira issues from one project key into a release's WorkItems.

    Only issues whose ``affectsVersion`` matches the release's ``version``
    are synced.  Issues with no affectsVersion set in JIRA are also included
    as a fallback so unversioned tickets are not lost.
    """
    release = db.query(Release).filter(Release.release_id == release_id).first()
    if not release:
        raise HTTPException(status_code=404, detail="Release not found")

    try:
        raw_issues = fetch_project_issues(project_key)
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Jira API error: {exc}") from exc

    # Filter issues to only those matching this release's version.
    release_version = (release.version or "").strip()
    if release_version and release_version.upper() != "UNVERSIONED":
        norm_rel_ver = release_version.lstrip("vV").lower()
        raw_issues = [
            issue for issue in raw_issues
            if issue.get("selected_version")
            and issue["selected_version"].lstrip("vV").lower() == norm_rel_ver
        ]

    existing_keys = {
        row.issue_key
        for row in db.query(WorkItem.issue_key)
        .filter(WorkItem.release_id == release_id)
        .all()
    }

    newly_synced = 0
    already_existed = 0
    response_issues: list[JiraIssue] = []

    for issue in raw_issues:
        affects_ver = issue.get("selected_version") or None
        jira_issue = JiraIssue(
            key=issue["key"],
            summary=issue["summary"],
            status=issue["status"],
            priority=issue["priority"],
            assignee=issue["assignee"],
            issue_type=issue["issue_type"],
            release_id=release_id,
            affects_version=affects_ver,
        )

        if issue["key"] in existing_keys:
            work_item = db.query(WorkItem).filter(
                WorkItem.issue_key == issue["key"],
                WorkItem.release_id == release_id,
            ).first()
            if work_item:
                work_item.title = issue["summary"]
                work_item.status = issue["status"]
                work_item.priority = issue["priority"] if issue["priority"] else "Medium"
                work_item.assigned_to = issue["assignee"]
                work_item.issue_type = issue["issue_type"]
                work_item.affects_version = affects_ver
            already_existed += 1
            response_issues.append(jira_issue)
            continue

        db.add(
            WorkItem(
                release_id=release_id,
                issue_key=issue["key"],
                title=issue["summary"],
                status=issue["status"],
                priority=issue["priority"] if issue["priority"] else "Medium",
                assigned_to=issue["assignee"],
                issue_type=issue["issue_type"],
                affects_version=affects_ver,
            )
        )
        newly_synced += 1
        existing_keys.add(issue["key"])
        response_issues.append(jira_issue)

    total_work_items = db.query(WorkItem).filter(WorkItem.release_id == release_id).count()
    release.total_work_items = total_work_items

    db.commit()

    return JiraSyncResponse(
        total_fetched=len(raw_issues),
        newly_synced=newly_synced,
        already_existed=already_existed,
        issues=response_issues,
    )


@router.get("/projects/{project_key}/issues", response_model=list[JiraIssue])
def list_jira_issues(project_key: str):
    """Fetch live Jira issues for one project key without persisting."""
    try:
        issues = fetch_project_issues(project_key)
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Jira API error: {exc}") from exc
    return [
        JiraIssue(
            key=i["key"],
            summary=i["summary"],
            status=i["status"],
            priority=i.get("priority"),
            assignee=i.get("assignee"),
            issue_type=i.get("issue_type"),
            release_id=i.get("release_id"),
            affects_version=i.get("selected_version"),
        )
        for i in issues
    ]


@router.post(
    "/releases/{release_id}/sync",
    response_model=JiraSyncResponse,
    status_code=status.HTTP_200_OK,
)
def sync_jira_to_release(
    release_id: int,
    body: JiraSyncRequest,
    db: Session = Depends(get_db),
):
    """Sync Jira issues from a provided project key into a release."""
    return _sync_project_issues_to_release(release_id, body.project_key, db)


@router.get("/releases/{release_id}/issues", response_model=list[JiraIssue])
def list_synced_jira_issues(release_id: int, db: Session = Depends(get_db)):
    """List Jira-synced WorkItems for a release."""
    items = db.query(WorkItem).filter(WorkItem.release_id == release_id).all()
    return [
        JiraIssue(
            key=item.issue_key,
            summary=item.title,
            status=item.status,
            priority=item.priority,
            assignee=item.assigned_to,
            issue_type=item.issue_type,
            release_id=item.release_id,
        )
        for item in items
    ]


@router.post("/releases/{release_id}/sync-from-project", response_model=JiraSyncResponse)
def sync_from_linked_project(release_id: int, db: Session = Depends(get_db)):
    """Sync Jira issues using the jira_project key configured on the release project."""
    release = (
        db.query(Release)
        .join(Project, Release.project_id == Project.project_id)
        .filter(Release.release_id == release_id)
        .first()
    )

    if not release:
        raise HTTPException(status_code=404, detail="Release not found")

    if not release.project or not release.project.jira_project:
        raise HTTPException(
            status_code=400,
            detail="No Jira project key set on this release's project. Set jira_project on the project first.",
        )

    return _sync_project_issues_to_release(release_id, release.project.jira_project, db)


@router.post("/workspace/sync", response_model=JiraWorkspaceSyncResponse)
def sync_workspace(db: Session = Depends(get_db)):
    """Sync all Jira workspace projects and related issues into local DB tables."""
    return _sync_workspace_projects_and_issues(db)


# Generated by GitHub Copilot
@router.post("/recalculate-counts")
def recalculate_all_counts(db: Session = Depends(get_db)):
    """
    Recalculate and update total_work_items count for all releases.
    
    This endpoint fixes discrepancies between Jira issue counts and database counts
    by recounting all work items per release and updating the totals.
    """
    try:
        # Get all releases
        releases = db.query(Release).all()
        
        updated_count = 0
        for release in releases:
            # Count work items for this release
            work_item_count = db.query(WorkItem).filter(
                WorkItem.release_id == release.release_id
            ).count()
            
            # Update release total
            if release.total_work_items != work_item_count:
                logger.info(
                    f"Updating Release {release.release_id}: "
                    f"total_work_items {release.total_work_items} → {work_item_count}"
                )
                release.total_work_items = work_item_count
                updated_count += 1
        
        db.commit()
        
        return {
            "total_releases": len(releases),
            "releases_updated": updated_count,
            "message": f"Successfully recalculated counts for {updated_count} releases",
        }
    except Exception as exc:
        logger.error(f"Error recalculating counts: {exc}")
        db.rollback()
        raise HTTPException(status_code=500, detail=f"Error recalculating counts: {exc}")


# Generated by GitHub Copilot
@router.post("/releases/{release_id}/recalculate-counts")
def recalculate_release_counts(release_id: int, db: Session = Depends(get_db)):
    """
    Recalculate and update work item count for a specific release.
    
    This endpoint fixes the tile counts on the release dashboard by
    recounting all work items linked to this release.
    """
    try:
        release = db.query(Release).filter(Release.release_id == release_id).first()
        if not release:
            raise HTTPException(status_code=404, detail="Release not found")
        
        # Count all work items for this release
        work_item_count = db.query(WorkItem).filter(
            WorkItem.release_id == release_id
        ).count()
        
        old_count = release.total_work_items
        release.total_work_items = work_item_count
        db.commit()
        
        logger.info(
            f"Recalculated Release {release_id}: "
            f"total_work_items {old_count} → {work_item_count}"
        )
        
        return {
            "release_id": release_id,
            "old_count": old_count,
            "new_count": work_item_count,
            "updated": old_count != work_item_count,
        }
    except Exception as exc:
        logger.error(f"Error recalculating counts for release {release_id}: {exc}")
        db.rollback()
        raise HTTPException(
            status_code=500,
            detail=f"Error recalculating counts: {exc}"
        )


# Generated by GitHub Copilot
@router.post("/releases/{release_id}/full-sync")
def full_sync_release_with_project(release_id: int, db: Session = Depends(get_db)):
    """
    Complete sync for a release:
    1. Fetch the linked Jira project key
    2. Sync ALL issues from that project
    3. Recalculate work item counts
    4. Return comprehensive summary
    """
    try:
        release = (
            db.query(Release)
            .join(Project, Release.project_id == Project.project_id)
            .filter(Release.release_id == release_id)
            .first()
        )
        
        if not release:
            raise HTTPException(status_code=404, detail="Release not found")
        
        if not release.project or not release.project.jira_project:
            raise HTTPException(
                status_code=400,
                detail="No Jira project key set on this release's project",
            )
        
        project_key = release.project.jira_project
        
        # Sync issues from Jira
        sync_result = _sync_project_issues_to_release(release_id, project_key, db)
        
        # Recalculate counts
        new_count = db.query(WorkItem).filter(
            WorkItem.release_id == release_id
        ).count()
        release.total_work_items = new_count
        db.commit()
        
        logger.info(f"Full sync complete for Release {release_id}: {new_count} work items")
        
        return {
            "release_id": release_id,
            "project_key": project_key,
            "sync_result": {
                "total_fetched": sync_result.total_fetched,
                "newly_synced": sync_result.newly_synced,
                "already_existed": sync_result.already_existed,
            },
            "final_work_item_count": new_count,
            "message": f"Synced {sync_result.newly_synced} new and "
                       f"updated {sync_result.already_existed} existing issues. "
                       f"Total: {new_count}",
        }
    except HTTPException:
        raise
    except Exception as exc:
        logger.error(f"Error in full sync for release {release_id}: {exc}")
        raise HTTPException(status_code=500, detail=f"Error: {exc}")


# Generated by GitHub Copilot
@router.post(
    "/work-items/remap-by-affects-version",
    summary="Remap work items to releases by their JIRA Affects Version",
)
def remap_work_items_by_affects_version(
    project_key: str = "AFCI",
    db: Session = Depends(get_db),
):
    """Fetch live JIRA issues, read their ``Affects Version`` field, match it
    against ``core.releases.version``, and update ``release_id`` on every
    matching work item in ``core.work_items``.

    Matching is case-insensitive with optional leading 'v' stripped
    (e.g. JIRA "v1.0.0" matches release version "1.0.0" or "v1.0.0").

    Returns a per-version breakdown of rows updated.
    """
    try:
        issues = fetch_project_issues(project_key)
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Jira API error: {exc}") from exc

    try:
        # Ensure affects_version column exists — add it if not present
        with engine.connect() as _conn:
            _driver = engine.url.get_backend_name()
            if _driver == "sqlite":
                _cols = [row[1] for row in _conn.execute(text("PRAGMA table_info(work_items)")).fetchall()]
                if "affects_version" not in _cols:
                    _conn.execute(text("ALTER TABLE work_items ADD COLUMN affects_version VARCHAR(100)"))
                    _conn.commit()
            else:
                _exists = _conn.execute(text("""
                    SELECT column_name FROM information_schema.columns
                    WHERE table_schema = 'core'
                      AND table_name   = 'work_items'
                      AND column_name  = 'affects_version'
                """)).fetchone()
                if not _exists:
                    _conn.execute(text("ALTER TABLE core.work_items ADD COLUMN affects_version VARCHAR(100)"))
                    _conn.commit()
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Migration error: {exc}") from exc

    try:
        releases = db.query(Release).all()
        version_map: dict[str, Release] = {}
        for rel in releases:
            if rel.version and rel.version.upper() != "UNVERSIONED":
                version_map[rel.version.lstrip("vV").lower()] = rel

        summary: dict[str, dict] = {}
        total_updated = 0
        not_matched: list[str] = []

        for issue in issues:
            issue_key: str = issue["key"]
            affects_ver: str | None = issue.get("selected_version")

            # Process ALL rows for this issue_key, not just the first
            all_rows = db.query(WorkItem).filter(WorkItem.issue_key == issue_key).all()

            if not all_rows:
                not_matched.append(f"{issue_key} (not in DB)")
                continue

            if not affects_ver:
                not_matched.append(f"{issue_key} (no Affects Version in JIRA)")
                # Still stamp affects_version=None on all rows
                for row in all_rows:
                    try:
                        row.affects_version = None
                    except Exception:
                        pass
                continue

            norm = affects_ver.lstrip("vV").lower()
            target_release = version_map.get(norm)
            if not target_release:
                not_matched.append(f"{issue_key} (version '{affects_ver}' not found in releases)")
                continue

            ver_label = affects_ver
            if ver_label not in summary:
                summary[ver_label] = {
                    "affects_version": ver_label,
                    "release_id": target_release.release_id,
                    "release_name": target_release.release_name,
                    "work_items_updated": 0,
                }

            # Stamp affects_version on all existing rows
            for row in all_rows:
                try:
                    row.affects_version = affects_ver
                except Exception:
                    pass

            correct_rows = [r for r in all_rows if r.release_id == target_release.release_id]
            wrong_rows = [r for r in all_rows if r.release_id != target_release.release_id]

            if correct_rows:
                # A correct row already exists — delete all wrong-release rows
                for row in wrong_rows:
                    db.delete(row)
                    total_updated += 1
                    summary[ver_label]["work_items_updated"] += 1
            else:
                # Move the first wrong row to the target release, delete the rest
                keep = wrong_rows[0]
                keep.release_id = target_release.release_id
                total_updated += 1
                summary[ver_label]["work_items_updated"] += 1
                for row in wrong_rows[1:]:
                    db.delete(row)

        db.commit()

        return {
            "total_updated": total_updated,
            "breakdown": list(summary.values()),
            "not_matched": not_matched,
        }
    except HTTPException:
        raise
    except Exception as exc:
        db.rollback()
        raise HTTPException(status_code=500, detail=f"Remap error: {exc}") from exc

