# Generated by GitHub Copilot
from typing import List
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from database import get_db
from models import Project
from project_filters import is_excluded_project_name
from schemas import ProjectCreate, ProjectUpdate, ProjectResponse

router = APIRouter(prefix="/projects", tags=["Projects"])


# Generated by GitHub Copilot
@router.post("/", response_model=ProjectResponse, status_code=status.HTTP_201_CREATED)
def create_project(project: ProjectCreate, db: Session = Depends(get_db)):
    """Create a project."""
    db_project = Project(**project.model_dump())
    db.add(db_project)
    db.commit()
    db.refresh(db_project)
    return db_project


# Generated by GitHub Copilot
@router.get("/", response_model=List[ProjectResponse])
def get_all_projects(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    """List projects."""
    projects = db.query(Project).offset(skip).limit(limit).all()
    return [p for p in projects if not is_excluded_project_name(p.project_name)]


# Generated by GitHub Copilot
@router.get("/{project_id}", response_model=ProjectResponse)
def get_project(project_id: int, db: Session = Depends(get_db)):
    """Fetch one project by id."""
    project = db.query(Project).filter(Project.project_id == project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    return project


# Generated by GitHub Copilot
@router.put("/{project_id}", response_model=ProjectResponse)
def update_project(project_id: int, project_data: ProjectUpdate, db: Session = Depends(get_db)):
    """Update one project by id."""
    project = db.query(Project).filter(Project.project_id == project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    update_fields = project_data.model_dump(exclude_unset=True)
    for field, value in update_fields.items():
        setattr(project, field, value)
    db.commit()
    db.refresh(project)
    return project


# Generated by GitHub Copilot
@router.delete("/{project_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_project(project_id: int, db: Session = Depends(get_db)):
    """Delete one project by id."""
    project = db.query(Project).filter(Project.project_id == project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    db.delete(project)
    db.commit()
