# Generated by GitHub Copilot
"""ReleaseHub governance routes."""

from datetime import datetime, timezone
from typing import List

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from sqlalchemy.orm import Session, joinedload

from bedrock_client import generate_release_summary, generate_branch_documentation
from github_client import get_branch_commits, get_branch_file_tree, get_file_content
import os
from urllib.parse import urlparse
from database import get_db
from models import AIAnalysis, PullRequest, Release, SecurityFinding, WorkItem, WorkflowAction
from schemas import (
    AIAnalysisResponse,
    AIAnalysisUpdate,
    PullRequestCreate,
    PullRequestResponse,
    PullRequestUpdate,
    ReadinessBreakdown,
    ReadinessCategoryScore,
    ReadinessScoreRequest,
    ReadinessScoreResponse,
    ReleaseDecision,
    ReleaseOverview,
    ReleaseResponse,
    SecurityFindingCreate,
    SecurityFindingResponse,
    SecurityFindingUpdate,
    WorkItemCreate,
    WorkItemResponse,
    WorkItemUpdate,
    WorkflowActionResponse,
)

router = APIRouter(prefix="/hub", tags=["ReleaseHub"])


# Generated by GitHub Copilot
def _get_release_or_404(release_id: int, db: Session) -> Release:
    """Load release or raise 404."""
    release = db.query(Release).options(joinedload(Release.project), joinedload(Release.manager)).filter(
        Release.release_id == release_id
    ).first()
    if not release:
        raise HTTPException(status_code=404, detail="Release not found")
    return release


# Generated by GitHub Copilot
def _release_to_response(r: Release, readiness_pct: int | None = None) -> ReleaseResponse:
    """Convert release model to API response."""
    owner = None
    if r.manager:
        owner = r.manager.name
    elif r.project and r.project.manager:
        owner = r.project.manager.name
    score = r.security_score
    rpt = readiness_pct if readiness_pct is not None else (int(score) if score is not None else 0)
    return ReleaseResponse(
        release_id=r.release_id,
        release_name=r.release_name,
        project_id=r.project_id,
        project_name=r.project.project_name if r.project else None,
        status=r.status,
        version=r.version,
        environment=r.environment,
        release_date=r.release_date,
        release_summary=r.release_summary,
        release_branch=r.release_branch,
        security_score=float(r.security_score) if r.security_score is not None else None,
        ai_risk_score=float(r.ai_risk_score) if r.ai_risk_score is not None else None,
        readiness_pct=rpt,
        owner=owner,
        target_date=r.release_date,
        created_at=r.created_date,
        go_no_go_override=r.go_no_go_override,
    )


# Generated by GitHub Copilot
def _work_item_to_response(w: WorkItem) -> WorkItemResponse:
    """Convert work item model to response with compatibility aliases."""
    return WorkItemResponse(
        work_item_id=w.work_item_id,
        release_id=w.release_id,
        issue_key=w.issue_key,
        title=w.title,
        issue_type=w.issue_type,
        priority=w.priority,
        status=w.status,
        assigned_to=w.assigned_to,
        jira_key=w.issue_key,
        severity=w.priority,
        defect_id=w.work_item_id,
    )


# Generated by GitHub Copilot
def _finding_to_response(f: SecurityFinding) -> SecurityFindingResponse:
    """Convert security finding model to response with compatibility aliases."""
    return SecurityFindingResponse(
        finding_id=f.finding_id,
        release_id=f.release_id,
        tool_name=f.tool_name,
        severity=f.severity,
        title=f.title,
        recommendation=f.recommendation,
        status=f.status,
        risk_id=f.finding_id,
        sec_id=f.tool_name,
        description=f.title,
    )


# Generated by GitHub Copilot
def _analysis_to_response(a: AIAnalysis) -> AIAnalysisResponse:
    """Convert AI analysis model to response with compatibility aliases."""
    return AIAnalysisResponse(
        analysis_id=a.analysis_id,
        release_id=a.release_id,
        pr_summary=a.pr_summary,
        release_notes=a.release_notes,
        risk_summary=a.risk_summary,
        overall_score=float(a.overall_score) if a.overall_score is not None else None,
        recommendation=a.recommendation,
        generated_time=a.generated_time,
        status=a.status or "GENERATED",
        doc_id=a.analysis_id,
        impact_summary=a.risk_summary,
        generated_at=a.generated_time,
    )


# Generated by GitHub Copilot
def _compute_readiness(prs: List[PullRequest], work_items: List[WorkItem], findings: List[SecurityFinding], analysis: AIAnalysis | None) -> ReadinessBreakdown:
    """Compute readiness 0-100 with four weighted categories."""
    pr_total = len(prs)
    pr_done = sum(1 for p in prs if p.status in ("Merged", "Closed"))
    pr_open = pr_total - pr_done
    if pr_total == 0:
        pr_score = 0
        pr_detail = "No PRs attached"
    else:
        pr_score = round((pr_done / pr_total) * 25)
        pr_detail = f"{pr_done} of {pr_total} merged / closed"
        if pr_open:
            pr_detail += f" ({pr_open} still open)"

    wi_total = len(work_items)
    wi_done = sum(1 for w in work_items if w.status == "Done")
    wi_open_hi = sum(1 for w in work_items if w.status != "Done" and (w.priority or "").lower() == "high")
    wi_open_lo = sum(1 for w in work_items if w.status != "Done" and (w.priority or "").lower() != "high")
    if wi_total == 0:
        def_score = 25
        def_detail = "No work items - clean slate"
    else:
        weighted_open = wi_open_hi * 2 + wi_open_lo
        weighted_total = wi_total + wi_open_hi
        def_score = max(0, round(25 - (weighted_open / weighted_total) * 25))
        def_detail = f"{wi_done} of {wi_total} done"
        if wi_open_hi:
            def_detail += f" ({wi_open_hi} High priority open)"

    f_total = len(findings)
    f_resolved = sum(1 for f in findings if f.status == "Resolved")
    f_open = f_total - f_resolved
    f_hi_open = sum(1 for f in findings if f.status != "Resolved" and (f.severity or "").lower() == "high")
    if f_total == 0:
        risk_score = 25
        risk_detail = "No security findings logged"
    else:
        risk_score = round((f_resolved / f_total) * 25)
        risk_detail = f"{f_resolved} of {f_total} resolved"
        if f_open:
            risk_detail += f" ({f_open} still open)"
            if f_hi_open:
                risk_detail += f", {f_hi_open} High severity"

    doc_st = (analysis.status or "NOT_GENERATED") if analysis else "NOT_GENERATED"
    if doc_st == "NOT_GENERATED" or analysis is None:
        doc_score = 0
        doc_detail = "Not generated yet"
    elif doc_st == "GENERATED":
        doc_score = 15
        doc_detail = "Generated - pending approval"
    else:
        doc_score = 25
        doc_detail = "Approved"

    total = pr_score + def_score + risk_score + doc_score

    open_wi = sum(1 for w in work_items if w.status != "Done")
    open_risks = sum(1 for f in findings if f.status != "Resolved")
    if open_wi > 0 or open_risks > 0:
        risk_level = "HIGH"
    elif total >= 80:
        risk_level = "LOW"
    else:
        risk_level = "MEDIUM"

    return ReadinessBreakdown(
        total=total,
        risk_level=risk_level,
        categories=[
            ReadinessCategoryScore(label="Pull Requests", score=pr_score, max_score=25, detail=pr_detail),
            ReadinessCategoryScore(label="Work Items", score=def_score, max_score=25, detail=def_detail),
            ReadinessCategoryScore(label="Security Risks", score=risk_score, max_score=25, detail=risk_detail),
            ReadinessCategoryScore(label="Documentation", score=doc_score, max_score=25, detail=doc_detail),
        ],
    )


# Generated by GitHub Copilot
def _compute_decision(work_items: List[WorkItem], findings: List[SecurityFinding], analysis: AIAnalysis | None, go_no_go_override: str | None = None) -> ReleaseDecision:
    """Compute release decision summary."""
    open_wi = sum(1 for w in work_items if w.status != "Done")
    open_risks = sum(1 for f in findings if f.status != "Resolved")
    doc_st = (analysis.status or "NOT_GENERATED") if analysis else "Not Generated"
    docs_status = doc_st.replace("_", " ").title()

    if go_no_go_override:
        go_no_go = go_no_go_override
    elif open_wi > 0 or open_risks > 0:
        go_no_go = "Blocked"
    elif analysis is None or doc_st == "NOT_GENERATED":
        go_no_go = "In Review"
    elif doc_st == "APPROVED":
        go_no_go = "Approved"
    else:
        go_no_go = "In Review"

    return ReleaseDecision(
        open_defects=open_wi,
        open_security_risks=open_risks,
        docs_status=docs_status,
        go_no_go=go_no_go,
    )


# Generated by GitHub Copilot
@router.get("/releases/{release_id}/overview", response_model=ReleaseOverview)
def get_release_overview(release_id: int, db: Session = Depends(get_db)):
    """Return release overview with readiness and decision."""
    release = _get_release_or_404(release_id, db)
    prs = db.query(PullRequest).filter(PullRequest.release_id == release_id).all()
    items = db.query(WorkItem).filter(WorkItem.release_id == release_id).all()
    findings = db.query(SecurityFinding).filter(SecurityFinding.release_id == release_id).all()
    analysis = db.query(AIAnalysis).filter(AIAnalysis.release_id == release_id).first()

    readiness = _compute_readiness(prs, items, findings, analysis)

    return ReleaseOverview(
        release=_release_to_response(release, readiness_pct=readiness.total),
        pull_requests=[PullRequestResponse.model_validate(p) for p in prs],
        defects=[_work_item_to_response(w) for w in items],
        security_risks=[_finding_to_response(f) for f in findings],
        doc=_analysis_to_response(analysis) if analysis else None,
        decision=_compute_decision(items, findings, analysis, release.go_no_go_override),
        readiness=readiness,
    )


# Generated by GitHub Copilot
class GoNoGoUpdate(BaseModel):
    """Request body for updating the Go/No-Go override."""
    go_no_go: str = ""


# Generated by GitHub Copilot
@router.patch("/releases/{release_id}/go-no-go")
def update_go_no_go(release_id: int, payload: GoNoGoUpdate, db: Session = Depends(get_db)):
    """Set the manual Go/No-Go override for a release."""
    valid = {"GO", "GO (Tentative)", "NO-GO", ""}
    value = payload.go_no_go
    if value not in valid:
        raise HTTPException(status_code=400, detail=f"Invalid value. Must be one of: {', '.join(v for v in valid if v)}")
    release = _get_release_or_404(release_id, db)
    release.go_no_go_override = value if value else None
    db.commit()
    return {"status": "ok", "go_no_go": value}


# Generated by GitHub Copilot
@router.get("/releases/{release_id}/pull-requests", response_model=List[PullRequestResponse])
def list_pull_requests(release_id: int, db: Session = Depends(get_db)):
    """List release pull requests."""
    _get_release_or_404(release_id, db)
    return db.query(PullRequest).filter(PullRequest.release_id == release_id).all()


# Generated by GitHub Copilot
@router.post("/releases/{release_id}/pull-requests", response_model=PullRequestResponse, status_code=status.HTTP_201_CREATED)
def add_pull_request(release_id: int, pr: PullRequestCreate, db: Session = Depends(get_db)):
    """Add pull request to release."""
    _get_release_or_404(release_id, db)
    db_pr = PullRequest(release_id=release_id, **pr.model_dump())
    db.add(db_pr)
    db.commit()
    db.refresh(db_pr)
    return db_pr


# Generated by GitHub Copilot
@router.put("/releases/{release_id}/pull-requests/{pr_id}", response_model=PullRequestResponse)
def update_pull_request(release_id: int, pr_id: int, pr_data: PullRequestUpdate, db: Session = Depends(get_db)):
    """Update pull request on release."""
    pr = db.query(PullRequest).filter(PullRequest.pr_id == pr_id, PullRequest.release_id == release_id).first()
    if not pr:
        raise HTTPException(status_code=404, detail="Pull request not found")
    for field, value in pr_data.model_dump(exclude_unset=True).items():
        setattr(pr, field, value)
    db.commit()
    db.refresh(pr)
    return pr


# Generated by GitHub Copilot
@router.delete("/releases/{release_id}/pull-requests/{pr_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_pull_request(release_id: int, pr_id: int, db: Session = Depends(get_db)):
    """Delete pull request from release."""
    pr = db.query(PullRequest).filter(PullRequest.pr_id == pr_id, PullRequest.release_id == release_id).first()
    if not pr:
        raise HTTPException(status_code=404, detail="Pull request not found")
    db.delete(pr)
    db.commit()


# Generated by GitHub Copilot
@router.get("/releases/{release_id}/defects", response_model=List[WorkItemResponse])
def list_defects(release_id: int, db: Session = Depends(get_db)):
    """List release defects/work items."""
    _get_release_or_404(release_id, db)
    return [_work_item_to_response(w) for w in db.query(WorkItem).filter(WorkItem.release_id == release_id).all()]


# Generated by GitHub Copilot
@router.post("/releases/{release_id}/defects", response_model=WorkItemResponse, status_code=status.HTTP_201_CREATED)
def add_defect(release_id: int, item: WorkItemCreate, db: Session = Depends(get_db)):
    """Add work item to release."""
    _get_release_or_404(release_id, db)
    db_item = WorkItem(release_id=release_id, **item.model_dump())
    db.add(db_item)
    db.commit()
    db.refresh(db_item)
    return _work_item_to_response(db_item)


# Generated by GitHub Copilot
@router.put("/releases/{release_id}/defects/{defect_id}", response_model=WorkItemResponse)
def update_defect(release_id: int, defect_id: int, item_data: WorkItemUpdate, db: Session = Depends(get_db)):
    """Update work item in release."""
    item = db.query(WorkItem).filter(WorkItem.work_item_id == defect_id, WorkItem.release_id == release_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Work item not found")
    for field, value in item_data.model_dump(exclude_unset=True).items():
        setattr(item, field, value)
    db.commit()
    db.refresh(item)
    return _work_item_to_response(item)


# Generated by GitHub Copilot
@router.delete("/releases/{release_id}/defects/{defect_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_defect(release_id: int, defect_id: int, db: Session = Depends(get_db)):
    """Delete work item from release."""
    item = db.query(WorkItem).filter(WorkItem.work_item_id == defect_id, WorkItem.release_id == release_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Work item not found")
    db.delete(item)
    db.commit()


# Generated by GitHub Copilot
@router.get("/releases/{release_id}/security-risks", response_model=List[SecurityFindingResponse])
def list_security_risks(release_id: int, db: Session = Depends(get_db)):
    """List release security findings."""
    _get_release_or_404(release_id, db)
    return [_finding_to_response(f) for f in db.query(SecurityFinding).filter(SecurityFinding.release_id == release_id).all()]


# Generated by GitHub Copilot
@router.post("/releases/{release_id}/security-risks", response_model=SecurityFindingResponse, status_code=status.HTTP_201_CREATED)
def add_security_risk(release_id: int, finding: SecurityFindingCreate, db: Session = Depends(get_db)):
    """Add security finding to release."""
    _get_release_or_404(release_id, db)
    db_f = SecurityFinding(release_id=release_id, **finding.model_dump())
    db.add(db_f)
    db.commit()
    db.refresh(db_f)
    return _finding_to_response(db_f)


# Generated by GitHub Copilot
@router.put("/releases/{release_id}/security-risks/{risk_id}", response_model=SecurityFindingResponse)
def update_security_risk(release_id: int, risk_id: int, data: SecurityFindingUpdate, db: Session = Depends(get_db)):
    """Update security finding in release."""
    finding = db.query(SecurityFinding).filter(SecurityFinding.finding_id == risk_id, SecurityFinding.release_id == release_id).first()
    if not finding:
        raise HTTPException(status_code=404, detail="Security finding not found")
    for field, value in data.model_dump(exclude_unset=True).items():
        setattr(finding, field, value)
    db.commit()
    db.refresh(finding)
    return _finding_to_response(finding)


# Generated by GitHub Copilot
@router.delete("/releases/{release_id}/security-risks/{risk_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_security_risk(release_id: int, risk_id: int, db: Session = Depends(get_db)):
    """Delete security finding from release."""
    finding = db.query(SecurityFinding).filter(SecurityFinding.finding_id == risk_id, SecurityFinding.release_id == release_id).first()
    if not finding:
        raise HTTPException(status_code=404, detail="Security finding not found")
    db.delete(finding)
    db.commit()


# Generated by GitHub Copilot
@router.get("/releases/{release_id}/docs", response_model=AIAnalysisResponse)
def get_docs(release_id: int, db: Session = Depends(get_db)):
    """Get release AI docs."""
    _get_release_or_404(release_id, db)
    analysis = db.query(AIAnalysis).filter(AIAnalysis.release_id == release_id).first()
    if not analysis:
        raise HTTPException(status_code=404, detail="No documentation found for this release")
    return _analysis_to_response(analysis)


# Generated by GitHub Copilot
@router.post("/releases/{release_id}/docs/generate", response_model=AIAnalysisResponse, status_code=status.HTTP_201_CREATED)
def generate_docs(release_id: int, db: Session = Depends(get_db)):
    """Generate docs through Bedrock client and persist analysis."""
    release = _get_release_or_404(release_id, db)
    prs = db.query(PullRequest).filter(PullRequest.release_id == release_id).all()
    items = db.query(WorkItem).filter(WorkItem.release_id == release_id).all()
    findings = db.query(SecurityFinding).filter(SecurityFinding.release_id == release_id).all()

    owner = None
    if release.manager:
        owner = release.manager.name
    elif release.project and release.project.manager:
        owner = release.project.manager.name

    context = {
        "release_name": release.release_name,
        "version": release.version,
        "owner": owner,
        "target_date": str(release.release_date) if release.release_date else None,
        "project_name": release.project.project_name if release.project else None,
        "project_description": None,
        "release_summary": release.release_summary,
        "pull_requests": [
            {"pr_number": str(p.pr_number), "title": p.title or "", "status": p.status or ""}
            for p in prs
        ],
        "defects": [
            {"jira_key": w.issue_key, "title": w.title or "", "severity": w.priority or "Medium", "status": w.status or "Open"}
            for w in items
        ],
        "security_risks": [
            {"sec_id": f.tool_name or str(f.finding_id), "description": f.title or "", "status": f.status or "Open"}
            for f in findings
        ],
    }

    try:
        notes, impact_text = generate_release_summary(context)
    except RuntimeError as exc:
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail=f"Bedrock generation failed: {exc}")

    analysis = db.query(AIAnalysis).filter(AIAnalysis.release_id == release_id).first()
    if analysis:
        analysis.release_notes = notes
        analysis.risk_summary = impact_text
        analysis.status = "GENERATED"
        analysis.generated_time = datetime.now(timezone.utc)
    else:
        analysis = AIAnalysis(
            release_id=release_id,
            release_notes=notes,
            risk_summary=impact_text,
            status="GENERATED",
            generated_time=datetime.now(timezone.utc),
        )
        db.add(analysis)

    db.commit()
    db.refresh(analysis)
    return _analysis_to_response(analysis)


# ── Branch-based documentation generation (added from v3) ──────────────────

def _parse_github_branch_url(url: str) -> tuple[str, str, str]:
    """
    Parse owner, repo, and branch name from a GitHub branch URL.

    Supports:
      https://github.com/{owner}/{repo}/commits/{branch}/
      https://github.com/{owner}/{repo}/tree/{branch}
      https://github.com/{owner}/{repo}/compare/{branch}
    """
    parsed = urlparse(url.rstrip("/"))
    parts  = [p for p in parsed.path.strip("/").split("/") if p]
    # parts: [owner, repo, segment, branch, ...]
    if len(parts) >= 4 and parts[2] in ("commits", "tree", "compare"):
        return parts[0], parts[1], parts[3]
    if len(parts) >= 3 and parts[2] in ("commits", "tree", "compare"):
        raise ValueError(f"Branch name missing in GitHub URL: {url}")
    raise ValueError(
        f"Unrecognised GitHub branch URL format: '{url}'. "
        "Expected https://github.com/{{owner}}/{{repo}}/commits/{{branch}}/"
    )


@router.post(
    "/releases/{release_id}/docs/generate-from-branch",
    response_model=AIAnalysisResponse,
    status_code=status.HTTP_201_CREATED,
)
def generate_docs_from_branch(release_id: int, db: Session = Depends(get_db)):
    """
    Generate technical documentation directly from the release's linked GitHub branch.
    release.release_branch must be a GitHub URL such as:
      https://github.com/owner/repo/tree/branch-name
    Owner, repo, and branch are parsed from the URL automatically.
    GITHUB_TOKEN env var is used for authentication.
    """
    release = _get_release_or_404(release_id, db)

    branch_url = release.release_branch
    if not branch_url:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Release has no release_branch set. Save a GitHub branch URL in the release first.",
        )

    try:
        gh_owner, gh_repo, branch = _parse_github_branch_url(branch_url)
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        )

    gh_token = os.environ.get("GITHUB_TOKEN")

    # ── Fetch branch data ──────────────────────────────────────────────────
    raw_commits = get_branch_commits(gh_owner, gh_repo, branch, token=gh_token)
    commits = [
        {
            "sha": c.get("sha", ""),
            "message": c.get("commit", {}).get("message", ""),
            "author": c.get("commit", {}).get("author", {}).get("name", "unknown"),
            "date": c.get("commit", {}).get("author", {}).get("date", ""),
        }
        for c in raw_commits
    ]

    file_tree  = get_branch_file_tree(gh_owner, gh_repo, branch, token=gh_token)
    file_paths = [f["path"] for f in file_tree]

    # Fetch source files (Python / JS / TS / Java / Go / C# / Ruby), cap at 10
    source_extensions = (".py", ".js", ".ts", ".java", ".go", ".cs", ".rb")
    source_files = [p for p in file_paths if p.endswith(source_extensions)]
    file_contents: dict[str, str] = {}
    for path in source_files[:10]:
        content = get_file_content(gh_owner, gh_repo, path, ref=branch, token=gh_token)
        if content:
            file_contents[path] = content

    # ── Build context ──────────────────────────────────────────────────────
    owner_name = None
    if release.manager:
        owner_name = release.manager.name
    elif release.project and release.project.manager:
        owner_name = release.project.manager.name

    context = {
        "repo_url": f"https://github.com/{gh_owner}/{gh_repo}",
        "branch": branch,
        "release_name": release.release_name,
        "version": release.version,
        "owner": owner_name,
        "commits": commits,
        "files": file_paths,
        "file_contents": file_contents,
    }

    try:
        notes, impact_text = generate_branch_documentation(context)
    except RuntimeError as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"Branch documentation generation failed: {exc}",
        )

    analysis = db.query(AIAnalysis).filter(AIAnalysis.release_id == release_id).first()
    if analysis:
        analysis.release_notes  = notes
        analysis.risk_summary   = impact_text
        analysis.status         = "GENERATED"
        analysis.generated_time = datetime.now(timezone.utc)
    else:
        analysis = AIAnalysis(
            release_id=release_id,
            release_notes=notes,
            risk_summary=impact_text,
            status="GENERATED",
            generated_time=datetime.now(timezone.utc),
        )
        db.add(analysis)

    db.commit()
    db.refresh(analysis)
    return _analysis_to_response(analysis)


# Generated by GitHub Copilot
@router.put("/releases/{release_id}/docs", response_model=AIAnalysisResponse)
def update_docs(release_id: int, doc_data: AIAnalysisUpdate, db: Session = Depends(get_db)):
    """Update release docs fields."""
    analysis = db.query(AIAnalysis).filter(AIAnalysis.release_id == release_id).first()
    if not analysis:
        raise HTTPException(status_code=404, detail="No documentation found for this release")
    for field, value in doc_data.model_dump(exclude_unset=True).items():
        setattr(analysis, field, value)
    db.commit()
    db.refresh(analysis)
    return _analysis_to_response(analysis)


# Generated by GitHub Copilot
@router.post("/releases/{release_id}/docs/approve", response_model=AIAnalysisResponse)
def approve_docs(release_id: int, db: Session = Depends(get_db)):
    """Approve generated docs for release."""
    analysis = db.query(AIAnalysis).filter(AIAnalysis.release_id == release_id).first()
    if not analysis or analysis.status == "NOT_GENERATED":
        raise HTTPException(status_code=400, detail="Docs must be generated before approving")
    analysis.status = "APPROVED"
    db.commit()
    db.refresh(analysis)
    return _analysis_to_response(analysis)


# Generated by GitHub Copilot
@router.get("/releases/{release_id}/workflow-actions", response_model=List[WorkflowActionResponse])
def list_workflow_actions(release_id: int, db: Session = Depends(get_db)):
    """List workflow actions for release."""
    _get_release_or_404(release_id, db)
    return db.query(WorkflowAction).filter(WorkflowAction.release_id == release_id).all()


# Generated by GitHub Copilot
@router.post("/readiness-score", response_model=ReadinessScoreResponse)
def compute_readiness_score(payload: ReadinessScoreRequest):
    """Standalone readiness score calculator without DB access."""
    from datetime import date as date_type

    prs = payload.pull_requests
    defects = payload.defects
    risks = payload.security_risks

    pr_total = len(prs)
    if pr_total == 0:
        pr_score, pr_detail = 0, "No pull requests provided"
    else:
        pr_done = sum(1 for p in prs if p.status in ("Merged", "Closed"))
        pr_score = round((pr_done / pr_total) * 25)
        pr_detail = f"{pr_done} of {pr_total} merged/closed"

    wi_total = len(defects)
    if wi_total == 0:
        def_score, def_detail = 25, "No defects - clean slate"
    else:
        wi_done = sum(1 for d in defects if d.status == "Done")
        wi_hi_open = sum(1 for d in defects if d.status != "Done" and (d.priority or "").lower() == "high")
        wi_lo_open = sum(1 for d in defects if d.status != "Done" and (d.priority or "").lower() != "high")
        weighted_open = wi_hi_open * 2 + wi_lo_open
        weighted_total = wi_total + wi_hi_open
        def_score = max(0, round(25 - (weighted_open / weighted_total) * 25))
        def_detail = f"{wi_done} of {wi_total} done"
        if wi_hi_open:
            def_detail += f" ({wi_hi_open} High priority open)"

    r_total = len(risks)
    if r_total == 0:
        risk_score, risk_detail = 25, "No security risks provided"
    else:
        r_resolved = sum(1 for r in risks if r.status == "Resolved")
        r_open = r_total - r_resolved
        risk_score = round((r_resolved / r_total) * 25)
        risk_detail = f"{r_resolved} of {r_total} resolved"
        if r_open:
            risk_detail += f" ({r_open} still open)"

    doc_score, doc_detail = 0, "Not provided (standalone mode)"

    total = pr_score + def_score + risk_score + doc_score

    open_wi_cnt = sum(1 for d in defects if d.status != "Done")
    open_r_cnt = sum(1 for r in risks if r.status != "Resolved")
    if open_wi_cnt > 0 or open_r_cnt > 0:
        risk_level = "HIGH"
    elif total >= 80:
        risk_level = "LOW"
    else:
        risk_level = "MEDIUM"

    readiness = ReadinessBreakdown(
        total=total,
        categories=[
            ReadinessCategoryScore(label="Pull Requests", score=pr_score, max_score=25, detail=pr_detail),
            ReadinessCategoryScore(label="Work Items", score=def_score, max_score=25, detail=def_detail),
            ReadinessCategoryScore(label="Security Risks", score=risk_score, max_score=25, detail=risk_detail),
            ReadinessCategoryScore(label="Documentation", score=doc_score, max_score=25, detail=doc_detail),
        ],
        risk_level=risk_level,
    )

    days_to_target = None
    if payload.target_date:
        days_to_target = (payload.target_date - date_type.today()).days

    return ReadinessScoreResponse(
        readiness=readiness,
        target_date=payload.target_date,
        days_to_target=days_to_target,
    )
