from typing import List
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session, joinedload

from database import get_db
from models import Release, Project
from project_filters import is_excluded_project_name
from schemas import ReleaseCreate, ReleaseUpdate, ReleaseResponse

router = APIRouter(prefix="/releases", tags=["Releases"])


def _to_response(r: Release) -> ReleaseResponse:
    """Normalize release model to response schema."""
    owner = None
    if r.manager:
        owner = r.manager.name
    elif r.project and r.project.manager:
        owner = r.project.manager.name
    score = r.security_score
    readiness_pct = int(score) if score is not None else 0
    return ReleaseResponse(
        release_id=r.release_id,
        release_name=r.release_name,
        project_id=r.project_id,
        project_name=r.project.project_name if r.project else None,
        status=r.status,
        version=r.version,
        environment=r.environment,
        release_date=r.release_date,
        release_summary=r.release_summary,
        security_score=float(r.security_score) if r.security_score is not None else None,
        ai_risk_score=float(r.ai_risk_score) if r.ai_risk_score is not None else None,
        readiness_pct=readiness_pct,
        owner=owner,
        target_date=r.release_date,
        created_at=r.created_date,
    )


# Generated by GitHub Copilot
@router.get("/", response_model=List[ReleaseResponse])
def get_all_releases(db: Session = Depends(get_db)):
    """List releases."""
    releases = db.query(Release).options(joinedload(Release.project), joinedload(Release.manager)).all()
    releases = [
        r for r in releases
        if not is_excluded_project_name(r.project.project_name if r.project else None)
    ]
    return [_to_response(r) for r in releases]


# Generated by GitHub Copilot
@router.post("/", response_model=ReleaseResponse, status_code=status.HTTP_201_CREATED)
def create_release(release: ReleaseCreate, db: Session = Depends(get_db)):
    """
    Create a release.
    
    Ensures:
    - release_id is auto-generated
    - project_id is properly validated
    - release is immediately available with all auto-generated fields
    """
    # Validate project exists if project_id is provided
    if release.project_id:
        project = db.query(Project).filter(Project.project_id == release.project_id).first()
        if not project:
            raise HTTPException(status_code=400, detail="Project not found")
    
    # Create release with auto-generated release_id
    db_release = Release(**release.model_dump())
    db.add(db_release)
    db.flush()  # Ensures release_id is auto-generated
    db.commit()
    db.refresh(db_release)
    
    # Fetch complete release with project relationship loaded
    r = db.query(Release).options(joinedload(Release.project)).filter(
        Release.release_id == db_release.release_id
    ).first()
    return _to_response(r)


# Generated by GitHub Copilot
@router.get("/{release_id}", response_model=ReleaseResponse)
def get_release(release_id: int, db: Session = Depends(get_db)):
    """Fetch one release by id."""
    r = db.query(Release).options(joinedload(Release.project), joinedload(Release.manager)).filter(
        Release.release_id == release_id
    ).first()
    if not r:
        raise HTTPException(status_code=404, detail="Release not found")
    return _to_response(r)


# Generated by GitHub Copilot
@router.put("/{release_id}", response_model=ReleaseResponse)
def update_release(release_id: int, release_data: ReleaseUpdate, db: Session = Depends(get_db)):
    """Update one release by id."""
    r = db.query(Release).filter(Release.release_id == release_id).first()
    if not r:
        raise HTTPException(status_code=404, detail="Release not found")
    for field, value in release_data.model_dump(exclude_unset=True).items():
        setattr(r, field, value)
    db.commit()
    r = db.query(Release).options(joinedload(Release.project), joinedload(Release.manager)).filter(
        Release.release_id == release_id
    ).first()
    return _to_response(r)


# Generated by GitHub Copilot
@router.delete("/{release_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_release(release_id: int, db: Session = Depends(get_db)):
    """Delete one release by id."""
    r = db.query(Release).filter(Release.release_id == release_id).first()
    if not r:
        raise HTTPException(status_code=404, detail="Release not found")
    db.delete(r)
    db.commit()
