# Generated by GitHub Copilot
"""Service helpers for GitHub integration and pull request synchronization."""

from __future__ import annotations

import importlib
import logging
import os
import re
from datetime import datetime
from pathlib import Path
from typing import Any

from sqlalchemy.orm import Session

import github_client
from models import Project, PullRequest, Release
from services.jira_service import get_issue_release_map

logger = logging.getLogger(__name__)

JIRA_KEY_PATTERN = re.compile(r"\b([A-Z][A-Z0-9]+-\d+)\b")


# Generated by GitHub Copilot
def _load_env() -> None:
    """Load .env when python-dotenv is installed, without hard dependency."""
    if importlib.util.find_spec("dotenv") is None:
        return

    dotenv = importlib.import_module("dotenv")
    dotenv.load_dotenv(Path(__file__).resolve().parents[1] / ".env")


_load_env()

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_OWNER = os.getenv("GITHUB_OWNER") or os.getenv("OWNER")
GITHUB_REPO = os.getenv("GITHUB_REPO") or os.getenv("REPO")


# Generated by GitHub Copilot
def _default_repo_full_name() -> str | None:
    """Build default owner/repo from environment values."""
    if GITHUB_OWNER and GITHUB_REPO:
        return f"{GITHUB_OWNER}/{GITHUB_REPO}"
    return None


# Generated by GitHub Copilot
def _parse_repo_owner_name(repository: str) -> tuple[str, str] | None:
    """Validate and split owner/repo string, using default owner when omitted."""
    if not repository:
        return None

    if "/" in repository:
        owner, repo = repository.split("/", 1)
    elif GITHUB_OWNER:
        owner, repo = GITHUB_OWNER, repository
    else:
        return None

    owner = owner.strip()
    repo = repo.strip()
    if not owner or not repo:
        return None
    return owner, repo


# Generated by GitHub Copilot
def _canonical_repo_name(repository: str) -> str:
    """Normalize repository to owner/repo form when possible."""
    parsed = _parse_repo_owner_name(repository)
    if not parsed:
        return repository.strip()
    owner, repo = parsed
    return f"{owner}/{repo}"


# Generated by GitHub Copilot
def _repo_from_release(db: Session, release_id: int) -> str | None:
    """Resolve repository name for a release from project config or env default."""
    release = db.query(Release).filter(Release.release_id == release_id).first()
    if not release:
        return None

    project = db.query(Project).filter(Project.project_id == release.project_id).first()
    if project and project.repository_name:
        return _canonical_repo_name(project.repository_name)

    fallback = _default_repo_full_name()
    return _canonical_repo_name(fallback) if fallback else None


# Generated by GitHub Copilot
def _status_from_pr(pr_detail: dict[str, Any]) -> str:
    """Map GitHub state fields to Open/Closed/Merged."""
    if pr_detail.get("merged_at"):
        return "Merged"
    state = (pr_detail.get("state") or "open").lower()
    if state == "closed":
        return "Closed"
    return "Open"


# Generated by GitHub Copilot
def _to_dt(value: str | None) -> datetime | None:
    """Convert GitHub ISO timestamp to datetime."""
    if not value:
        return None
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


# Generated by GitHub Copilot
def _extract_jira_keys_from_text(value: str | None) -> list[str]:
    """Extract Jira issue keys from text while preserving first-seen order."""
    if not value:
        return []
    found = JIRA_KEY_PATTERN.findall(value.upper())
    unique: list[str] = []
    for key in found:
        if key not in unique:
            unique.append(key)
    return unique


# Generated by GitHub Copilot
def _extract_jira_ref(detail: dict[str, Any], commits: list[dict[str, Any]]) -> str | None:
    """
    Extract Jira reference using priority order: title, branch, body, commit messages.

    Security note:
    - Only reads textual metadata already available in GitHub API payloads.
    """
    candidates: list[str] = []
    candidates.extend(_extract_jira_keys_from_text(detail.get("title")))
    candidates.extend(_extract_jira_keys_from_text((detail.get("head") or {}).get("ref")))
    candidates.extend(_extract_jira_keys_from_text(detail.get("body")))

    for commit in commits:
        message = ((commit.get("commit") or {}).get("message")) or ""
        candidates.extend(_extract_jira_keys_from_text(message))

    return candidates[0] if candidates else None


# Generated by GitHub Copilot
def _release_id_from_jira_map(db: Session, jira_ref: str | None) -> int | None:
    """Reuse Jira work-item mapping to resolve release from Jira issue key."""
    if not jira_ref:
        return None
    mapped = get_issue_release_map(db, [jira_ref])
    return mapped.get(jira_ref)


# Generated by GitHub Copilot
def _resolve_project_from_repo(db: Session, repository: str) -> Project | None:
    """Resolve project by exact or short repository name mapping."""
    canonical = _canonical_repo_name(repository).lower()
    short_name = canonical.split("/", 1)[1] if "/" in canonical else canonical

    projects = db.query(Project).filter(Project.repository_name.isnot(None)).all()
    for project in projects:
        repo_name = (project.repository_name or "").strip()
        if not repo_name:
            continue
        normalized = _canonical_repo_name(repo_name).lower()
        normalized_short = normalized.split("/", 1)[1] if "/" in normalized else normalized
        if canonical == normalized or short_name == normalized_short:
            return project
    return None


# Generated by GitHub Copilot
def _resolve_release_id(
    db: Session,
    repository: str,
    explicit_release_id: int | None,
    explicit_project_id: int | None,
    jira_ref: str | None,
) -> int | None:
    """
    Resolve release mapping for one PR.

    Priority:
    1. Explicit release_id input
    2. Jira issue key to existing WorkItem.release_id mapping
    3. Latest release for explicit project_id
    4. Latest release for repository-mapped project
    """
    if explicit_release_id is not None:
        return explicit_release_id

    mapped_release_id = _release_id_from_jira_map(db, jira_ref)
    if mapped_release_id is not None:
        return mapped_release_id

    project: Project | None = None
    if explicit_project_id is not None:
        project = db.query(Project).filter(Project.project_id == explicit_project_id).first()
    if project is None:
        project = _resolve_project_from_repo(db, repository)
    if project is None:
        return None

    release = (
        db.query(Release)
        .filter(Release.project_id == project.project_id)
        .order_by(Release.release_id.desc())
        .first()
    )
    return release.release_id if release else None


# Generated by GitHub Copilot
def _upsert_pull_request(
    db: Session,
    repository: str,
    pr_number: int,
    payload: dict[str, Any],
) -> str:
    """
    Upsert one PR by unique business key (repository, pr_number).

    Returns one of: inserted, updated, skipped.
    """
    row = db.query(PullRequest).filter(
        PullRequest.repository == repository,
        PullRequest.pr_number == pr_number,
    ).first()

    if row is None:
        if payload.get("release_id") is None:
            return "skipped"
        db.add(PullRequest(pr_number=pr_number, **payload))
        return "inserted"

    changed = False
    for field, value in payload.items():
        if getattr(row, field) != value:
            setattr(row, field, value)
            changed = True

    return "updated" if changed else "skipped"


# Generated by GitHub Copilot
def _sync_repository(
    db: Session,
    repository: str,
    state: str,
    explicit_release_id: int | None = None,
    explicit_project_id: int | None = None,
) -> dict[str, Any]:
    """Sync all PRs for one repository with insert/update/skip counts."""
    parsed = _parse_repo_owner_name(repository)
    if not parsed:
        return {
            "repository": repository,
            "fetched": 0,
            "inserted": 0,
            "updated": 0,
            "skipped": 0,
            "errors": ["Invalid repository format; expected owner/repo or configured default owner"],
        }

    owner, repo = parsed
    canonical_repo = f"{owner}/{repo}"

    logger.info("GitHub PR synchronization started for repository %s", canonical_repo)
    prs = github_client.get_pull_requests(owner, repo, token=GITHUB_TOKEN, state=state)
    logger.info("Repository %s: fetched %s pull requests", canonical_repo, len(prs))

    inserted = 0
    updated = 0
    skipped = 0
    errors: list[str] = []

    for pr in prs:
        pr_number = pr.get("number")
        if pr_number is None:
            skipped += 1
            continue

        detail = github_client.get_pull_request(owner, repo, int(pr_number), token=GITHUB_TOKEN)
        if not detail:
            detail = pr

        commits = github_client.get_pull_request_commits(owner, repo, int(pr_number), token=GITHUB_TOKEN)
        jira_ref = _extract_jira_ref(detail, commits)
        resolved_release_id = _resolve_release_id(
            db,
            repository=canonical_repo,
            explicit_release_id=explicit_release_id,
            explicit_project_id=explicit_project_id,
            jira_ref=jira_ref,
        )

        payload = {
            "release_id": resolved_release_id,
            "title": detail.get("title") or pr.get("title"),
            "author": ((detail.get("user") or {}).get("login")) or ((pr.get("user") or {}).get("login")),
            "repository": canonical_repo,
            "status": _status_from_pr(detail),
            "lines_added": detail.get("additions"),
            "lines_deleted": detail.get("deletions"),
            "merged_date": _to_dt(detail.get("merged_at")),
            "jira_ref": jira_ref,
            "github_url": detail.get("html_url") or pr.get("html_url"),
            "created_at": _to_dt(detail.get("created_at") or pr.get("created_at")),
            "milestone_version": ((detail.get("milestone") or pr.get("milestone") or {}).get("title")),
        }

        # Priority 1: GitHub milestone title (most authoritative)
        # Priority 2: version string extracted from the PR title  (e.g. "… v2.0.0")
        # Priority 3: release.version as final fallback
        if not payload["milestone_version"]:
            pr_title: str = payload.get("title") or ""
            _ver_match = re.search(r"v(\d+\.\d+(?:\.\d+)?)\s*$", pr_title, re.IGNORECASE)
            if _ver_match:
                payload["milestone_version"] = _ver_match.group(0).strip()

        if not payload["milestone_version"] and resolved_release_id:
            _rel = db.query(Release).filter(Release.release_id == resolved_release_id).first()
            if _rel and _rel.version and _rel.version.upper() != "UNVERSIONED":
                payload["milestone_version"] = _rel.version

        try:
            action = _upsert_pull_request(db, canonical_repo, int(pr_number), payload)
        except Exception as exc:  # noqa: BLE001
            errors.append(f"PR {pr_number}: {exc}")
            logger.exception("Failed to upsert PR %s for repository %s", pr_number, canonical_repo)
            continue

        if action == "inserted":
            inserted += 1
        elif action == "updated":
            updated += 1
        else:
            skipped += 1

    logger.info(
        "Repository %s sync completed. fetched=%s inserted=%s updated=%s skipped=%s errors=%s",
        canonical_repo,
        len(prs),
        inserted,
        updated,
        skipped,
        len(errors),
    )

    return {
        "repository": canonical_repo,
        "fetched": len(prs),
        "inserted": inserted,
        "updated": updated,
        "skipped": skipped,
        "errors": errors,
    }


# Generated by GitHub Copilot
def get_pull_requests(repository: str | None = None, state: str = "open") -> list[dict[str, Any]]:
    """Fetch pull requests from GitHub API for one repository."""
    repo_full_name = repository or _default_repo_full_name()
    parsed = _parse_repo_owner_name(repo_full_name or "")
    if not parsed:
        return []

    owner, repo = parsed
    return github_client.get_pull_requests(owner, repo, token=GITHUB_TOKEN, state=state)


# Generated by GitHub Copilot
def get_pull_request(pr_number: int, repository: str | None = None) -> dict[str, Any]:
    """Fetch one pull request from GitHub API."""
    repo_full_name = repository or _default_repo_full_name()
    parsed = _parse_repo_owner_name(repo_full_name or "")
    if not parsed:
        return {}

    owner, repo = parsed
    return github_client.get_pull_request(owner, repo, pr_number, token=GITHUB_TOKEN)


# Generated by GitHub Copilot
def _sync_and_commit(
    db: Session,
    repositories: list[str],
    state: str,
    explicit_release_id: int | None = None,
    explicit_project_id: int | None = None,
) -> dict[str, Any]:
    """Sync one or many repositories and commit once for consistency."""
    logger.info("GitHub PR synchronization started for %s repositories", len(repositories))
    total_fetched = 0
    total_inserted = 0
    total_updated = 0
    total_skipped = 0
    per_repo: list[dict[str, Any]] = []

    try:
        for repository in repositories:
            result = _sync_repository(
                db,
                repository=repository,
                state=state,
                explicit_release_id=explicit_release_id,
                explicit_project_id=explicit_project_id,
            )
            total_fetched += result["fetched"]
            total_inserted += result["inserted"]
            total_updated += result["updated"]
            total_skipped += result["skipped"]
            per_repo.append(result)

        db.commit()
    except Exception as exc:  # noqa: BLE001
        db.rollback()
        logger.exception("GitHub PR synchronization failed and transaction was rolled back")
        return {
            "state": state,
            "repositories_processed": len(repositories),
            "fetched": total_fetched,
            "inserted": total_inserted,
            "updated": total_updated,
            "skipped": total_skipped,
            "details": per_repo,
            "error": str(exc),
        }

    if explicit_release_id is not None:
        release = db.query(Release).filter(Release.release_id == explicit_release_id).first()
        if release:
            release.total_prs = db.query(PullRequest).filter(PullRequest.release_id == explicit_release_id).count()
            db.commit()

    logger.info(
        "GitHub PR synchronization completed. fetched=%s inserted=%s updated=%s skipped=%s",
        total_fetched,
        total_inserted,
        total_updated,
        total_skipped,
    )

    return {
        "state": state,
        "repositories_processed": len(repositories),
        "fetched": total_fetched,
        "inserted": total_inserted,
        "updated": total_updated,
        "skipped": total_skipped,
        "details": per_repo,
    }


# Generated by GitHub Copilot
def sync_pull_requests(db: Session, release_id: int, state: str = "all") -> dict[str, Any]:
    """Sync GitHub pull requests into local DB for a specific release."""
    release = db.query(Release).filter(Release.release_id == release_id).first()
    if not release:
        return {"message": "Release not found"}

    repo_full_name = _repo_from_release(db, release_id)
    if not repo_full_name:
        return {"message": "Repository is not configured for this release/project"}

    result = _sync_and_commit(
        db,
        repositories=[repo_full_name],
        state=state,
        explicit_release_id=release_id,
        explicit_project_id=release.project_id,
    )
    result["release_id"] = release_id
    result["repository"] = repo_full_name
    return result


# Generated by GitHub Copilot
def sync_project_pull_requests(
    db: Session,
    project_id: int,
    state: str = "all",
    release_id: int | None = None,
) -> dict[str, Any]:
    """Sync pull requests for a project using its repository mapping."""
    project = db.query(Project).filter(Project.project_id == project_id).first()
    if not project:
        return {"message": "Project not found"}
    if not project.repository_name:
        return {"message": "Project repository_name is not configured"}

    if release_id is not None:
        target_release = db.query(Release).filter(Release.release_id == release_id).first()
        if not target_release:
            return {"message": "Release not found"}

    repository = _canonical_repo_name(project.repository_name)
    result = _sync_and_commit(
        db,
        repositories=[repository],
        state=state,
        explicit_release_id=release_id,
        explicit_project_id=project_id,
    )
    result["project_id"] = project_id
    result["repository"] = repository
    if release_id is not None:
        result["release_id"] = release_id
    return result


# Generated by GitHub Copilot
def sync_all_mapped_pull_requests(
    db: Session,
    state: str = "all",
    release_id: int | None = None,
) -> dict[str, Any]:
    """Sync pull requests for all projects that have configured repository mappings."""
    repositories: list[str] = []

    if release_id is not None:
        target_release = db.query(Release).filter(Release.release_id == release_id).first()
        if not target_release:
            return {"message": "Release not found"}

    for repo_name, in db.query(Project.repository_name).filter(Project.repository_name.isnot(None)).all():
        if repo_name:
            repositories.append(_canonical_repo_name(repo_name))

    fallback = _default_repo_full_name()
    if fallback:
        repositories.append(_canonical_repo_name(fallback))

    unique_repositories = sorted({repo for repo in repositories if repo})
    if not unique_repositories:
        return {"message": "No repository mappings found"}

    result = _sync_and_commit(
        db,
        repositories=unique_repositories,
        state=state,
        explicit_release_id=release_id,
    )
    if release_id is not None:
        result["release_id"] = release_id
    return result


# Generated by GitHub Copilot
def remap_all_pull_requests_to_release(db: Session, release_id: int) -> dict[str, Any]:
    """
    Force-map all stored pull requests to one release id.

    This utility supports one-time migration or explicit operational remapping.
    """
    release = db.query(Release).filter(Release.release_id == release_id).first()
    if not release:
        return {"message": "Release not found"}

    rows = db.query(PullRequest).all()
    total = len(rows)
    updated = 0

    for row in rows:
        if row.release_id != release_id:
            row.release_id = release_id
            updated += 1

    release.total_prs = total
    db.commit()

    logger.info(
        "All pull requests remapped to release_id=%s. total=%s updated=%s",
        release_id,
        total,
        updated,
    )

    return {
        "release_id": release_id,
        "total_pull_requests": total,
        "remapped": updated,
        "unchanged": total - updated,
    }


# Generated by GitHub Copilot
def get_release_pull_requests(db: Session, release_id: int) -> list[PullRequest]:
    """Return locally stored pull requests for one release."""
    return db.query(PullRequest).filter(PullRequest.release_id == release_id).all()
