# Generated by GitHub Copilot
"""Service helpers for Jira integration."""

import importlib
import os
from pathlib import Path
from typing import Any

import requests
from requests.auth import HTTPBasicAuth
from sqlalchemy.orm import Session

from models import Project, Release, WorkItem
from project_filters import is_excluded_project_name


def _load_env() -> None:
    """Load .env when python-dotenv is installed, without hard dependency."""
    if importlib.util.find_spec("dotenv") is None:
        return

    dotenv = importlib.import_module("dotenv")
    dotenv.load_dotenv(Path(__file__).resolve().parents[1] / ".env")


_load_env()

JIRA_URL = (os.getenv("JIRA_URL") or "").rstrip("/")
JIRA_EMAIL = os.getenv("JIRA_EMAIL")
JIRA_TOKEN = os.getenv("JIRA_TOKEN")

JIRA_PROJECTS_API = "/rest/api/3/project"
JIRA_ISSUE_SEARCH_API = "/rest/api/3/search/jql"
JIRA_ISSUE_DETAILS_API = "/rest/api/3/issue/{issue_key}"
ISSUE_FIELDS = "summary,issuetype,priority,status,assignee,project,affectsVersions,versions,fixVersions"
ISSUE_DETAIL_FIELDS = "summary,description,issuetype,priority,status,assignee,project"


# Generated by GitHub Copilot
def _jira_get(path: str, params: dict[str, Any] | None = None) -> dict[str, Any] | list[dict[str, Any]]:
    """Run a Jira GET call and return JSON payload, or an empty structure on failure."""
    if not JIRA_URL or not JIRA_EMAIL or not JIRA_TOKEN:
        return [] if path == JIRA_PROJECTS_API else {}

    try:
        response = requests.get(
            f"{JIRA_URL}{path}",
            auth=HTTPBasicAuth(JIRA_EMAIL, JIRA_TOKEN),
            headers={"Accept": "application/json"},
            params=params,
            timeout=20,
        )
    except requests.RequestException:
        return [] if path == JIRA_PROJECTS_API else {}

    if response.status_code != 200:
        return [] if path == JIRA_PROJECTS_API else {}

    try:
        return response.json()
    except ValueError:
        return [] if path == JIRA_PROJECTS_API else {}


# Generated by GitHub Copilot
def get_live_projects() -> list[dict[str, Any]]:
    """Fetch Jira projects from Jira Cloud."""
    payload = _jira_get(JIRA_PROJECTS_API)
    return payload if isinstance(payload, list) else []


# Generated by GitHub Copilot
def get_stored_projects(db: Session) -> list[Project]:
    """Return locally stored projects that have a configured Jira key."""
    rows = (
        db.query(Project)
        .filter(Project.jira_project.isnot(None))
        .order_by(Project.project_name.asc())
        .all()
    )
    return [row for row in rows if not is_excluded_project_name(row.project_name)]


# Generated by GitHub Copilot
def sync_projects(db: Session) -> dict[str, int]:
    """Upsert Jira projects into local project records by jira_project key."""
    jira_projects = get_live_projects()

    inserted = 0
    updated = 0

    for jira_project in jira_projects:
        project_key = jira_project.get("key")
        project_name = jira_project.get("name")

        if not project_key:
            continue
        if is_excluded_project_name(project_name):
            continue

        project = db.query(Project).filter(Project.jira_project == project_key).first()
        if project:
            if project_name and project.project_name != project_name:
                project.project_name = project_name
                updated += 1
            continue

        db.add(
            Project(
                project_name=project_name or project_key,
                jira_project=project_key,
            )
        )
        inserted += 1

    db.commit()

    return {
        "total_from_jira": len(jira_projects),
        "inserted": inserted,
        "updated": updated,
    }


# Generated by GitHub Copilot
def _search_issues(project_key: str, start_at: int = 0, max_results: int = 50) -> dict[str, Any]:
    """Fetch one Jira issue page for a given project key."""
    payload = _jira_get(
        JIRA_ISSUE_SEARCH_API,
        params={
            "jql": f"project={project_key} ORDER BY created DESC",
            "startAt": start_at,
            "maxResults": max_results,
            "fields": ISSUE_FIELDS,
        },
    )
    return payload if isinstance(payload, dict) else {}


# Generated by GitHub Copilot
def get_issues(project_key: str) -> list[dict[str, Any]]:
    """
    Fetch latest issues for a Jira project.

    Returns all issues regardless of whether they have a Jira version id.
    """
    payload = _search_issues(project_key, max_results=50)
    issues = payload.get("issues", [])
    return issues


# Generated by GitHub Copilot
def get_issue(issue_key: str) -> dict[str, Any]:
    """Fetch a single Jira issue by key."""
    payload = _jira_get(
        JIRA_ISSUE_DETAILS_API.format(issue_key=issue_key),
        params={"fields": ISSUE_DETAIL_FIELDS},
    )
    return payload if isinstance(payload, dict) else {}


# Generated by GitHub Copilot
def resolve_release_for_project_and_version(
    db: Session,
    project_id: int,
    version: str | None,
) -> Release | None:
    """
    Resolve a Release for a given Project and Version.
    
    Returns:
    - Existing Release if (project_id, version) exists
    - None if project doesn't exist or version is invalid
    """
    if not project_id or not version:
        return None
    
    release = (
        db.query(Release)
        .filter(
            Release.project_id == project_id,
            Release.version == version,
        )
        .first()
    )
    return release


# Generated by GitHub Copilot
def create_or_get_release(
    db: Session,
    project_id: int,
    version: str | None,
    release_name: str | None = None,
) -> Release | None:
    """
    Create or get a Release for a given Project and Version.
    
    Logic:
    1. If version is None, use "UNVERSIONED"
    2. Query for existing (project_id, version) pair
    3. If exists: return it
    4. If not exists: create new Release with auto-generated release_id
    
    Returns:
    - Release object with populated release_id (auto-generated)
    - None if project doesn't exist
    """
    if not project_id:
        return None
    
    version_value = version or "UNVERSIONED"
    
    # Check if release already exists
    existing = (
        db.query(Release)
        .filter(
            Release.project_id == project_id,
            Release.version == version_value,
        )
        .first()
    )
    
    if existing:
        return existing
    
    # Get project to use its name as release name
    project = db.query(Project).filter(Project.project_id == project_id).first()
    if not project:
        return None
    
    # Create new release
    new_release = Release(
        project_id=project_id,
        release_name=release_name or project.project_name,
        version=version_value,
        status="In Progress",
    )
    db.add(new_release)
    db.flush()  # Ensures release_id is auto-generated
    
    return new_release


# Generated by GitHub Copilot
def _resolve_release_id(db: Session, project_key: str, release_id: int | None) -> int | None:
    """Resolve the release id for issue sync using explicit id or latest release by Jira project."""
    if release_id is not None:
        release = db.query(Release).filter(Release.release_id == release_id).first()
        return release.release_id if release else None

    project = db.query(Project).filter(Project.jira_project == project_key).first()
    if not project:
        return None

    latest_release = (
        db.query(Release)
        .filter(Release.project_id == project.project_id)
        .order_by(Release.release_id.desc())
        .first()
    )
    return latest_release.release_id if latest_release else None


# Generated by GitHub Copilot
def sync_project_issues(db: Session, project_key: str, release_id: int | None = None) -> dict[str, Any]:
    """Upsert Jira issues for one project into core.work_items."""
    issues = get_issues(project_key)
    target_release_id = _resolve_release_id(db, project_key, release_id)

    inserted = 0
    updated = 0

    for issue in issues:
        fields = issue.get("fields", {})
        issue_key = issue.get("key")
        if not issue_key:
            continue

        assignee = fields.get("assignee") or {}
        issue_type = fields.get("issuetype") or {}
        priority = fields.get("priority") or {}
        status = fields.get("status") or {}

        payload = {
            "title": fields.get("summary") or issue_key,
            "issue_type": issue_type.get("name"),
            "priority": priority.get("name") or "Medium",
            "status": status.get("name") or "Open",
            "assigned_to": assignee.get("displayName") or "Unassigned",
        }

        work_item = db.query(WorkItem).filter(WorkItem.issue_key == issue_key).first()
        if work_item:
            for field, value in payload.items():
                setattr(work_item, field, value)
            if target_release_id is not None:
                work_item.release_id = target_release_id
            updated += 1
            continue

        if target_release_id is None:
            continue

        db.add(
            WorkItem(
                release_id=target_release_id,
                issue_key=issue_key,
                **payload,
            )
        )
        inserted += 1

    if target_release_id is not None:
        release = db.query(Release).filter(Release.release_id == target_release_id).first()
        if release:
            release.total_work_items = (
                db.query(WorkItem).filter(WorkItem.release_id == target_release_id).count()
            )

    db.commit()

    return {
        "project_key": project_key,
        "release_id": target_release_id,
        "fetched": len(issues),
        "inserted": inserted,
        "updated": updated,
    }


# Generated by GitHub Copilot
def sync_release_issues(db: Session, release_id: int) -> dict[str, Any]:
    """Sync Jira issues for the release's project into that release."""
    release = db.query(Release).filter(Release.release_id == release_id).first()
    if not release:
        return {"message": "Release not found"}

    project = db.query(Project).filter(Project.project_id == release.project_id).first()
    if not project or not project.jira_project:
        return {"message": "Project or Jira project key not configured"}

    return sync_project_issues(db, project.jira_project, release_id=release_id)


# Generated by GitHub Copilot
def get_release_issues(db: Session, release_id: int) -> list[WorkItem]:
    """Return locally stored work items for one release."""
    return db.query(WorkItem).filter(WorkItem.release_id == release_id).all()


# Generated by GitHub Copilot
def get_issue_release_map(db: Session, issue_keys: list[str]) -> dict[str, int | None]:
    """Map Jira issue keys to local release IDs."""
    if not issue_keys:
        return {}

    rows = (
        db.query(WorkItem.issue_key, WorkItem.release_id)
        .filter(WorkItem.issue_key.in_(issue_keys))
        .all()
    )
    return {issue_key: release_id for issue_key, release_id in rows}


# Generated by GitHub Copilot
def _extract_primary_version_id(issue_fields: dict[str, Any]) -> str | None:
    """Return the first available Jira version id from issue fields."""
    for field_name in ("affectsVersions", "versions", "fixVersions"):
        for version in issue_fields.get(field_name) or []:
            version_id = (version or {}).get("id")
            if version_id:
                return str(version_id)
    return None


# Generated by GitHub Copilot
def _resolve_release_id(db: Session, project_key: str, release_id: int | None, issue_fields: dict[str, Any] | None = None) -> int | None:
    """Resolve release id using explicit release id or Jira version-id-to-release mapping."""
    if release_id is not None:
        release = db.query(Release).filter(Release.release_id == release_id).first()
        return release.release_id if release else None

    project = db.query(Project).filter(Project.jira_project == project_key).first()
    if not project:
        return None

    version_id = _extract_primary_version_id(issue_fields or {})
    if not version_id:
        return None

    mapped_release = (
        db.query(Release)
        .filter(
            Release.project_id == project.project_id,
            Release.version == version_id,
        )
        .first()
    )
    return mapped_release.release_id if mapped_release else None


# Generated by GitHub Copilot
def sync_project_issues(db: Session, project_key: str, release_id: int | None = None) -> dict[str, Any]:
    """Upsert Jira issues into work_items only when issue has version id and mapped release exists."""
    issues = get_issues(project_key)

    inserted = 0
    updated = 0
    skipped = 0

    for issue in issues:
        fields = issue.get("fields", {})
        issue_key = issue.get("key")
        if not issue_key:
            skipped += 1
            continue

        target_release_id = _resolve_release_id(db, project_key, release_id, fields)
        if target_release_id is None:
            skipped += 1
            continue

        assignee = fields.get("assignee") or {}
        issue_type = fields.get("issuetype") or {}
        priority = fields.get("priority") or {}
        status = fields.get("status") or {}

        payload = {
            "title": fields.get("summary") or issue_key,
            "issue_type": issue_type.get("name"),
            "priority": priority.get("name") or "Medium",
            "status": status.get("name") or "Open",
            "assigned_to": assignee.get("displayName") or "Unassigned",
        }

        work_item = db.query(WorkItem).filter(WorkItem.issue_key == issue_key).first()
        if work_item:
            for field, value in payload.items():
                setattr(work_item, field, value)
            work_item.release_id = target_release_id
            updated += 1
            continue

        db.add(
            WorkItem(
                release_id=target_release_id,
                issue_key=issue_key,
                **payload,
            )
        )
        inserted += 1

    if release_id is not None:
        release = db.query(Release).filter(Release.release_id == release_id).first()
        if release:
            release.total_work_items = (
                db.query(WorkItem).filter(WorkItem.release_id == release_id).count()
            )

    db.commit()

    return {
        "project_key": project_key,
        "release_id": release_id,
        "fetched": len(issues),
        "inserted": inserted,
        "updated": updated,
        "skipped": skipped,
    }


# Generated by GitHub Copilot
def sync_release_issues(db: Session, release_id: int) -> dict[str, Any]:
    """Sync Jira issues for the release's project into that release."""
    release = db.query(Release).filter(Release.release_id == release_id).first()
    if not release:
        return {"message": "Release not found"}

    project = db.query(Project).filter(Project.project_id == release.project_id).first()
    if not project or not project.jira_project:
        return {"message": "Project or Jira project key not configured"}

    return sync_project_issues(db, project.jira_project, release_id=release_id)


# Generated by GitHub Copilot
def sync_project_issues(db: Session, project_key: str, release_id: int | None = None) -> dict[str, Any]:
    """Upsert Jira issues for one project into core.work_items."""
    issues = get_issues(project_key)
    target_release_id = _resolve_release_id(db, project_key, release_id)

    inserted = 0
    updated = 0

    for issue in issues:
        fields = issue.get("fields", {})
        issue_key = issue.get("key")
        if not issue_key:
            continue

        assignee = fields.get("assignee") or {}
        issue_type = fields.get("issuetype") or {}
        priority = fields.get("priority") or {}
        status = fields.get("status") or {}

        payload = {
            "title": fields.get("summary") or issue_key,
            "issue_type": issue_type.get("name"),
            "priority": priority.get("name") or "Medium",
            "status": status.get("name") or "Open",
            "assigned_to": assignee.get("displayName") or "Unassigned",
        }

        work_item = db.query(WorkItem).filter(WorkItem.issue_key == issue_key).first()
        if work_item:
            for field, value in payload.items():
                setattr(work_item, field, value)
            if target_release_id is not None:
                work_item.release_id = target_release_id
            updated += 1
            continue

        if target_release_id is None:
            continue

        db.add(
            WorkItem(
                release_id=target_release_id,
                issue_key=issue_key,
                **payload,
            )
        )
        inserted += 1

    if target_release_id is not None:
        release = db.query(Release).filter(Release.release_id == target_release_id).first()
        if release:
            release.total_work_items = (
                db.query(WorkItem).filter(WorkItem.release_id == target_release_id).count()
            )

    db.commit()

    return {
        "project_key": project_key,
        "release_id": target_release_id,
        "fetched": len(issues),
        "inserted": inserted,
        "updated": updated,
    }


# Generated by GitHub Copilot
def sync_release_issues(db: Session, release_id: int) -> dict[str, Any]:
    """Sync Jira issues for the release's project into that release."""
    release = db.query(Release).filter(Release.release_id == release_id).first()
    if not release:
        return {"message": "Release not found"}

    project = db.query(Project).filter(Project.project_id == release.project_id).first()
    if not project or not project.jira_project:
        return {"message": "Project or Jira project key not configured"}

    return sync_project_issues(db, project.jira_project, release_id=release_id)


# Generated by GitHub Copilot
def get_release_issues(db: Session, release_id: int) -> list[WorkItem]:
    """Return locally stored work items for one release."""
    return db.query(WorkItem).filter(WorkItem.release_id == release_id).all()


# Generated by GitHub Copilot
def get_issue_release_map(db: Session, issue_keys: list[str]) -> dict[str, int | None]:
    """Map Jira issue keys to local release IDs."""
    if not issue_keys:
        return {}

    rows = (
        db.query(WorkItem.issue_key, WorkItem.release_id)
        .filter(WorkItem.issue_key.in_(issue_keys))
        .all()
    )
    return {issue_key: release_id for issue_key, release_id in rows}
