# Generated by GitHub Copilot
"""GitHub REST API client utilities for fetching pull request and milestone data."""

import logging
from typing import Any

import requests

logger = logging.getLogger(__name__)

GITHUB_API_BASE = "https://api.github.com"


def _headers(token: str | None) -> dict[str, str]:
    headers = {
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


def get_pull_requests(
    owner: str,
    repo: str,
    token: str | None = None,
    state: str = "open",
    per_page: int = 100,
) -> list[dict[str, Any]]:
    """Fetch all pull requests for a repository using pagination."""
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/pulls"
    params: dict[str, Any] = {"state": state, "per_page": per_page, "page": 1}
    results: list[dict[str, Any]] = []

    while True:
        try:
            response = requests.get(url, headers=_headers(token), params=params, timeout=30)
            response.raise_for_status()
        except requests.RequestException as exc:
            logger.error("Failed to fetch pull requests for %s/%s: %s", owner, repo, exc)
            break

        page_data = response.json()
        if not page_data:
            break

        results.extend(page_data)

        if len(page_data) < per_page:
            break

        params["page"] += 1

    return results


def get_pull_request(
    owner: str,
    repo: str,
    pr_number: int,
    token: str | None = None,
) -> dict[str, Any]:
    """Fetch details of a single pull request."""
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/pulls/{pr_number}"
    try:
        response = requests.get(url, headers=_headers(token), timeout=30)
        response.raise_for_status()
        return response.json()
    except requests.RequestException as exc:
        logger.error("Failed to fetch PR %s for %s/%s: %s", pr_number, owner, repo, exc)
        return {}


def get_pull_request_commits(
    owner: str,
    repo: str,
    pr_number: int,
    token: str | None = None,
    per_page: int = 100,
) -> list[dict[str, Any]]:
    """Fetch commits associated with a pull request."""
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/pulls/{pr_number}/commits"
    params: dict[str, Any] = {"per_page": per_page, "page": 1}
    results: list[dict[str, Any]] = []

    while True:
        try:
            response = requests.get(url, headers=_headers(token), params=params, timeout=30)
            response.raise_for_status()
        except requests.RequestException as exc:
            logger.error("Failed to fetch commits for PR %s (%s/%s): %s", pr_number, owner, repo, exc)
            break

        page_data = response.json()
        if not page_data:
            break

        results.extend(page_data)

        if len(page_data) < per_page:
            break

        params["page"] += 1

    return results


# -- Branch utilities (added from v3) ----------------------------------------

def get_branch_commits(
    owner: str,
    repo: str,
    branch: str,
    token: str | None = None,
    per_page: int = 50,
) -> list[dict[str, Any]]:
    """Fetch the most recent commits on a branch (up to per_page)."""
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/commits"
    params: dict[str, Any] = {"sha": branch, "per_page": per_page, "page": 1}
    try:
        response = requests.get(url, headers=_headers(token), params=params, timeout=30)
        response.raise_for_status()
        return response.json()
    except requests.RequestException as exc:
        logger.error("Failed to fetch commits for branch %s (%s/%s): %s", branch, owner, repo, exc)
        return []


def get_branch_file_tree(
    owner: str,
    repo: str,
    branch: str,
    token: str | None = None,
) -> list[dict[str, Any]]:
    """Fetch the recursive file tree for a branch (blobs only)."""
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/git/trees/{branch}"
    params: dict[str, Any] = {"recursive": "1"}
    try:
        response = requests.get(url, headers=_headers(token), params=params, timeout=30)
        response.raise_for_status()
        data = response.json()
        return [item for item in data.get("tree", []) if item.get("type") == "blob"]
    except requests.RequestException as exc:
        logger.error("Failed to fetch file tree for branch %s (%s/%s): %s", branch, owner, repo, exc)
        return []


def get_file_content(
    owner: str,
    repo: str,
    path: str,
    ref: str,
    token: str | None = None,
) -> str:
    """Fetch decoded text content of a single file at a given ref."""
    import base64
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/contents/{path}"
    params: dict[str, Any] = {"ref": ref}
    try:
        response = requests.get(url, headers=_headers(token), params=params, timeout=30)
        response.raise_for_status()
        data = response.json()
        if data.get("encoding") == "base64":
            return base64.b64decode(data["content"]).decode("utf-8", errors="replace")
        return data.get("content", "")
    except requests.RequestException as exc:
        logger.error("Failed to fetch file %s@%s (%s/%s): %s", path, ref, owner, repo, exc)
        return ""


# -- Branch utilities (added from v3) ----------------------------------------

def get_branch_commits(
    owner: str,
    repo: str,
    branch: str,
    token: str | None = None,
    per_page: int = 50,
) -> list[dict[str, Any]]:
    """Fetch the most recent commits on a branch (up to per_page)."""
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/commits"
    params: dict[str, Any] = {"sha": branch, "per_page": per_page, "page": 1}
    try:
        response = requests.get(url, headers=_headers(token), params=params, timeout=30)
        response.raise_for_status()
        return response.json()
    except requests.RequestException as exc:
        logger.error("Failed to fetch commits for branch %s (%s/%s): %s", branch, owner, repo, exc)
        return []


def get_branch_file_tree(
    owner: str,
    repo: str,
    branch: str,
    token: str | None = None,
) -> list[dict[str, Any]]:
    """Fetch the recursive file tree for a branch (blobs only)."""
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/git/trees/{branch}"
    params: dict[str, Any] = {"recursive": "1"}
    try:
        response = requests.get(url, headers=_headers(token), params=params, timeout=30)
        response.raise_for_status()
        data = response.json()
        return [item for item in data.get("tree", []) if item.get("type") == "blob"]
    except requests.RequestException as exc:
        logger.error("Failed to fetch file tree for branch %s (%s/%s): %s", branch, owner, repo, exc)
        return []


def get_file_content(
    owner: str,
    repo: str,
    path: str,
    ref: str,
    token: str | None = None,
) -> str:
    """Fetch decoded text content of a single file at a given ref."""
    import base64
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/contents/{path}"
    params: dict[str, Any] = {"ref": ref}
    try:
        response = requests.get(url, headers=_headers(token), params=params, timeout=30)
        response.raise_for_status()
        data = response.json()
        if data.get("encoding") == "base64":
            return base64.b64decode(data["content"]).decode("utf-8", errors="replace")
        return data.get("content", "")
    except requests.RequestException as exc:
        logger.error("Failed to fetch file %s@%s (%s/%s): %s", path, ref, owner, repo, exc)
        return ""


# Generated by GitHub Copilot
def get_milestones(
    owner: str,
    repo: str,
    token: str | None = None,
    state: str = "all",
    per_page: int = 100,
) -> list[dict[str, Any]]:
    """Fetch all milestones for a repository.

    Each milestone title is expected to be a version string (e.g. ``v1.2.0``)
    that can be matched against the ``version`` column of the releases table.
    """
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/milestones"
    params: dict[str, Any] = {"state": state, "per_page": per_page, "page": 1}
    results: list[dict[str, Any]] = []

    while True:
        try:
            response = requests.get(url, headers=_headers(token), params=params, timeout=30)
            response.raise_for_status()
        except requests.RequestException as exc:
            logger.error("Failed to fetch milestones for %s/%s: %s", owner, repo, exc)
            break

        page_data = response.json()
        if not page_data:
            break

        results.extend(page_data)

        if len(page_data) < per_page:
            break

        params["page"] += 1

    return results
