# Generated by GitHub Copilot
"""Jira client utilities for fetching project issues."""

import os
from pathlib import Path

from dotenv import load_dotenv
from jira import JIRA

load_dotenv(Path(__file__).resolve().parent / ".env")


# Generated by GitHub Copilot
def get_jira_client() -> JIRA:
    """Create an authenticated Jira client from environment variables."""
    return JIRA(
        server=os.getenv("JIRA_URL"),
        basic_auth=(os.getenv("JIRA_EMAIL"), os.getenv("JIRA_TOKEN")),
    )


# Generated by GitHub Copilot
def fetch_workspace_projects() -> list[dict]:
    """Fetch all projects visible in the Jira workspace."""
    jira = get_jira_client()
    projects = jira.projects()

    result: list[dict] = []
    for project in projects:
        result.append(
            {
                "key": getattr(project, "key", None),
                "name": getattr(project, "name", None),
            }
        )

    return [project for project in result if project.get("key")]


# Generated by GitHub Copilot
def _extract_version_names(version_objects) -> list[str]:
    """Read version names from Jira issue version objects."""
    if not version_objects:
        return []

    names: list[str] = []
    for version in version_objects:
        name = getattr(version, "name", None)
        if name:
            names.append(name)
    return names


# Generated by GitHub Copilot
def _extract_version_ids(version_objects) -> list[str]:
    """Read version IDs from Jira issue version objects."""
    if not version_objects:
        return []

    ids: list[str] = []
    for version in version_objects:
        version_id = getattr(version, "id", None)
        if version_id is not None:
            ids.append(str(version_id))
    return ids


# Generated by GitHub Copilot
def _extract_version_pairs(version_objects) -> list[tuple[str | None, str | None]]:
    """Read (version_name, version_id) pairs from Jira issue version objects."""
    if not version_objects:
        return []

    pairs: list[tuple[str | None, str | None]] = []
    for version in version_objects:
        version_name = getattr(version, "name", None)
        version_id = getattr(version, "id", None)
        pairs.append((version_name, str(version_id) if version_id is not None else None))
    return pairs


# Generated by GitHub Copilot
def fetch_project_issues(project_key: str, max_results: int = 100) -> list[dict]:
    """
    Fetch Jira issues for a project and normalize fields for WorkItem sync.

    All issues are returned regardless of whether they have a version id.
    Issues without a version id will have selected_version and selected_version_id as None.
    """
    jira = get_jira_client()
    issues = jira.search_issues(
        f"project = {project_key} ORDER BY created DESC",
        maxResults=max_results,
        fields="summary,status,priority,assignee,issuetype,project,affectsVersions,versions,fixVersions",
    )

    result: list[dict] = []
    for issue in issues:
        fields = issue.fields

        raw_priority = getattr(getattr(fields, "priority", None), "name", None)
        raw_assignee = getattr(getattr(fields, "assignee", None), "displayName", None)
        raw_project_key = getattr(getattr(fields, "project", None), "key", project_key)
        raw_project_name = getattr(getattr(fields, "project", None), "name", project_key)

        affects_version_objs = getattr(fields, "affectsVersions", None)
        version_objs = getattr(fields, "versions", None)
        fix_version_objs = getattr(fields, "fixVersions", None)

        affects_versions = _extract_version_names(affects_version_objs)
        versions = _extract_version_names(version_objs)
        fix_versions = _extract_version_names(fix_version_objs)

        affects_version_ids = _extract_version_ids(affects_version_objs)
        version_ids = _extract_version_ids(version_objs)
        fix_version_ids = _extract_version_ids(fix_version_objs)

        selected_version = None
        selected_version_id = None
        version_pairs = [
            *_extract_version_pairs(affects_version_objs),
            *_extract_version_pairs(version_objs),
            *_extract_version_pairs(fix_version_objs),
        ]
        for version_name, version_id in version_pairs:
            if version_id or version_name:
                selected_version = version_name or None
                selected_version_id = version_id or None
                break

        result.append(
            {
                "key": issue.key,
                "summary": getattr(fields, "summary", issue.key),
                "status": getattr(getattr(fields, "status", None), "name", "Unknown"),
                "priority": raw_priority,
                "assignee": raw_assignee,
                "issue_type": getattr(getattr(fields, "issuetype", None), "name", None),
                "project_key": raw_project_key,
                "project_name": raw_project_name,
                "affects_versions": affects_versions,
                "versions": versions,
                "fix_versions": fix_versions,
                "affects_version_ids": affects_version_ids,
                "version_ids": version_ids,
                "fix_version_ids": fix_version_ids,
                "selected_version": selected_version,
                "selected_version_id": selected_version_id,
                "release_id": None,
            }
        )

    return result
