# Generated by GitHub Copilot
"""Shared project filtering helpers for API list and sync operations."""

EXCLUDED_PROJECT_NAMES = {
    "intelligent data platform",
    "aeh federal application analyzer",
    "cod_doed",
}


# Generated by GitHub Copilot
def is_excluded_project_name(project_name: str | None) -> bool:
    """Return True when a project name is configured to be excluded."""
    if not project_name:
        return False
    return project_name.strip().casefold() in EXCLUDED_PROJECT_NAMES
